### PR TITLE
Setup assets folder

### PR DESCRIPTION
**Pull request by gunamata**
Added a couple of samples to the e2e/assets folder for basic testing purposes.

### CODE REVIEW

**Review by mook-as — CHANGES_REQUESTED** [review]
We should be _doing_ something with assets, not just adding them to the repo as-is.

**Comment by gunamata** [comment]
My thought process is to have some simple setups that we can use as a starting point for QA (manual). I agree with you that we need to enhance e2e setup to automate running these samples.

**Comment by jandubois** [comment]
I'm feeling uneasy about adding GPL sample code into a repo that is under the Apache-2 license.

I see that the subdirectory has its own license file, but it still feels confusing to me.

@gunamata Did you write the samples yourself? If yes, why did you put it under GPL?

It adds 700 lines of license text for 15 line of "hello world" code.

@mattfarina What do you think?

**Comment by gunamata** [comment]
@jandubois , I used a nodejs framework called nest [https://nestjs.com/](url) and it's CLI to generate this sample app, all of the files are autogenerated by the CLI. If the license stuff creates confusion then I will replace this with a simpler nodejs sample.

**Comment by jandubois** [comment]
> If the license stuff creates confusion then I will replace this with a simpler nodejs sample.

I think so, but let @mattfarina decide what to do...

**Pull request closed without merging**
