### PR TITLE
Fix "delete_all_snapshots" and test snapshot names with metacharacters

### PR DESCRIPTION
**Pull request by jandubois**

### CODE REVIEW

**Review by ericpromislow — CHANGES_REQUESTED** [review]
Test failure:
```
✓ factory-reset doesn't delete a non-empty snapshots directory
 ✗ factory-reset does delete an empty snapshots directory
   (from function `assert_not_exists' in file bats/bats-file/src/file.bash, line 646,
    in test file bats/tests/snapshots/create-use-snapshot.bats, line 176)
     `assert_not_exists "$PATH_SNAPSHOTS"' failed
   time="2023-10-20T12:37:38-07:00" level=error msg="Ignoring error trying to get lima directory: can't find the lima-home directory at \"/home/ericp/.local/share/rancher-desktop/lima\""
   time="2023-10-20T12:37:38-07:00" level=error msg="Error trying to delete the Lima VM: can't find the lima-home directory at \"/home/ericp/.local/share/rancher-desktop/lima\"\n"
   
   -- file or directory exists, but it was expected to be absent --
   path : /home/ericp/.local/share/rancher-desktop/snapshots
   --
```

**Comment by jandubois** [comment]
> Test failure:

Doesn't seem related to this PR; I can repro the failure in `main`.

**Comment by jandubois** [comment]
> > Test failure:
> 
> Doesn't seem related to this PR; I can repro the failure in `main`.

Test failure was because I had an "incomplete" snapshot in the directory, so it wasn't really empty. So not a real failure.

**Review by ericpromislow — APPROVED** [review]
works fine now

**Pull request merged**
