### PR TITLE
Updated installing.md re Linux support

### PR DESCRIPTION
**Pull request by simonflood**
Rancher Desktop v0.6.0 includes a Technical Preview of Linux support.

### CODE REVIEW

**Comment by simonflood** [comment]
Not sure I can do this via the web interface, will have a play.

**Comment by simonflood** [comment]
Blimey more hurdles than in an Olympics final! Just tried fixing it (again)

**Comment by jandubois** [comment]
Unfortunately still doesn't work because you were adding just more commits to your branch, but didn't remove/replace the one without the signature.

Here is how I would fix this:

```console
# Make sure you are on your patch-1 branch
$ git checkout patch-1

# Verify the commit you want to keep
$ git show 6dd55308ae7dd16c018a2e9e22aedf335ba86963
commit 6dd55308ae7dd16c018a2e9e22aedf335ba86963
Author: Simon Flood <simonflood@users.noreply.github.com>
Date:   Tue Oct 12 17:43:22 2021 +0100

    Updated installing.md re Linux support

    Rancher Desktop v0.6.0 includes a Technical Preview of Linux support.

    Signed-off-by: Simon Flood <simonflood@users.noreply.github.com>

diff --git docs/installing.md docs/installing.md
index 458fb4c..75b3ad6 100644
--- docs/installing.md
+++ docs/installing.md
@@ -37,4 +37,4 @@ https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80370102-th

 ## Linux

-Linux is currently not supported.
+Rancher Desktop v0.6.0 includes a Technical Preview of Linux support. rpm, deb, and archive files are available for download.

# Make sure your upstream branch is up-to-date
$ git fetch origin

# Change your patch-1 branch to point to the latest main
$ git reset --hard origin/main

# Copy over just the single commit you want to keep
$ git cherry-pick 6dd55308ae7dd16c018a2e9e22aedf335ba86963
[patch-1 c7529c6] Updated installing.md re Linux support
 Author: Simon Flood <simonflood@users.noreply.github.com>
 Date: Tue Oct 12 17:43:22 2021 +0100
 1 file changed, 1 insertion(+), 1 deletion(-)

# Verify that everything is fine
$ git log -p
[...]

# Replace the PR branch on github
$ git push -f
```

**Comment by jandubois** [comment]
Thank you for your contribution (and sorry for the ordeal)!

**Pull request merged**
