### PR TITLE
308 link to kuberlr

### PR DESCRIPTION
**Pull request by ericpromislow**

### CODE REVIEW

**Review by mattfarina — COMMENTED** [review]
Has anyone tested kuberlr on Windows? When I spoke with Flavio, I got the impression it didn't work there.

**Comment by ericpromislow** [comment]
I think the problem might be that kuberlr relies on symlinks, and while I can create one on Windows pointing `kubectl.exe` to `kuberlr.exe`, I can't run it.  So very likely we won't be able to run it on windows

**Comment by jandubois** [comment]
> I think the problem might be that kuberlr relies on symlinks

I don't think it does rely on symlink; it is just a Unix thing to do, to avoid having multiple copies of the same file under different names.

It seems to work just fine for me:

```cmd
e:\home\jan>copy z:\jan\Downloads\kuberlr_0.3.1_windows_amd64\kuberlr.exe kubectl.exe
        1 file(s) copied.
e:\home\jan>.\kubectl help
I0611 16:30:53.575464    2580 versioner.go:58] invalid configuration: no configuration has been provided
I0611 16:30:53.575464    2580 versioner.go:64] No local kubectl binary found, fetching latest stable release version
I0611 16:30:53.731265    2580 versioner.go:84] Right kubectl missing, downloading version 1.21.1
Downloading https://storage.googleapis.com/kubernetes-release/release/v1.21.1/bin/windows/amd64/kubectl.exe
kubectl1.21.1.exe 100% |████████████████████████████████████████| (49/49 MB, 66.983 MB/s) [0s:0s] done.
kubectl controls the Kubernetes cluster manager.

 Find more information at: https://kubernetes.io/docs/reference/kubectl/overview/

Basic Commands (Beginner):
  create        Create a resource from a file or from stdin.
  expose        Take a replication controller, service, deployment or pod and expose it as a new Kubernetes Service
  run           Run a particular image on the cluster
  set           Set specific features on objects
[...]
e:\home\jan>dir c:\Users\Jan\.kuberlr\windows-amd64
 Volume in drive C has no label.
 Volume Serial Number is 5C37-CD74

 Directory of c:\Users\Jan\.kuberlr\windows-amd64

06/11/2021  04:30 PM    <DIR>          .
06/11/2021  04:30 PM    <DIR>          ..
06/11/2021  04:30 PM        48,951,296 kubectl1.21.1.exe
               1 File(s)     48,951,296 bytes
               2 Dir(s)  49,863,340,032 bytes free
```

So the only slightly weird thing is that it doesn't create the cache directory under my modified home directory, but under the original one. I would argue that the right place would be underneath `%LocalAppData%`, but not caring too much. We can always create a PR to fix it, if it creates problems for domain users.

**Comment by ericpromislow** [comment]
superseded by 308b

**Pull request closed without merging**
