### PR TITLE
Bump bundled utilities for release-1.17

### PR DESCRIPTION
**Pull request by jandubois**
Bump helm and docker-compose

### CODE REVIEW

**Comment by jandubois** [comment]
I've successfully tested this PR on macOS with

```
./bats-core/bin/bats tests/compose/* tests/extensions/* tests/k8s/wordpress.bats
```

**Comment by jandubois** [comment]
Converting it to draft for now: Let's collect all utility bump cherry-picks in this PR, and do a full BATS test before merging close to the release.

**Comment by jandubois** [comment]
I've run BATS for the CI build for this PR with macOS 15 on M1 for qemu with both containers and Moby, and all tests passed, except for `profile/invalid-locked-k8s-version`, which is a known issue (#7818).

**Review by mook-as — APPROVED** [review]
If there were more bumps before release we can always make new PRs.

**Pull request merged**
