### PR TITLE
Create lockable `rd-select` wrapper component

### LINKED ISSUE #4700: Display lock for dropdownlists
## 🔳 Acceptance Criteria

Given a select element on the preferences page:

- [ ] It can be locked.
- [ ] It displays a lock icon when it is locked.
- [ ] It is disabled when it is locked.
- [ ] It remains interactive (i.e., selectable and editable) when it is not locked.
- [ ] It visually indicates an unlocked state (e.g., no lock icon, normal appearance).
- [ ] It retains its current selected option when locked and unlocked.
- [ ] It triggers the appropriate actions or events based on the selected option, regardless of its locked state.
- [ ] It provides a clear indication to the user when attempting to interact with the input while it is locked (i.e., tooltip).

### PR DESCRIPTION
**Pull request by rak-phillip**
This creates an `rd-select` wrapper component that adds a locked state for `select` elements in the Preferences modal. 

This new component contributes to the addition of locked fields throughout Rancher Desktop via #4662

## 🗒️ Testing Notes

This PR covers the creation of the wrapper component and we don't currently have the ability apply a locked state via deployment profiles. Basic functionality can be confirmed by supplying the `:is-locked` prop to `rd-select`. Additional acceptance criteria detailed in associated issue. 

### Locked

image

### Disabled

image

### Default

image

closes #4700

### CODE REVIEW

**Comment by ericpromislow** [comment]
There's a regression I don't understand.  With settings of:
```
kubernetes: { enabled: false, version: '1.22.17' }
```

in `main` I see these values in the UI. The `enabled` checkbox is ... enabled(sorry) but unchecked, and the version string is disabled and shows `1.22.17`

In this PR, the `enabled` checkbox is the same, but the version field is disabled and set to `v1.26.4 (stable)`.

The value for `kubernetes.version` is still "1.22.17" so it looks like there's an error in the way the new dialog displays its value, but I don't see why. Everything still points to `this.preferences.kubernetes.version` which AFAICT is still "1.22.17", not "1.26.4"

**Review by ericpromislow — CHANGES_REQUESTED** [review]
Wrote up a regression at https://github.com/rancher-sandbox/rancher-desktop/pull/4706#issuecomment-1553504766

**Comment by rak-phillip** [comment]
@ericpromislow good catch, thank you! I've fixed the regression and the PR is ready for review again.

**Review by ericpromislow — APPROVED** [review]
looks good now

**Pull request merged**
