### PR TITLE
WSL: Use OpenRC.

### PR DESCRIPTION
**Pull request by mook-as**
This changes our WSL code to use OpenRC as well, like we do on mac.  This is preparation for #950.

Note that this requires a custom WSL distribution build until https://github.com/rancher-sandbox/rancher-desktop-wsl-distro/pull/17 is done.

### CODE REVIEW

**Review by mattfarina — COMMENTED** [review]
@mook-as can you please fix the linting issues.

Note, I tested the change and it works. I've not reviewed the source, though.

**Comment by mook-as** [comment]
Linting issues? They must not have never existing… :grin: (No, actually, I already force-pushed fixes.)

**Comment by ericpromislow** [comment]
Fails to run on macos. I get this error message at startup in `lima.log` with a clean system:

```
 * Starting Docker Daemon ... [ ok ]
 * rc-service: Permission denied
2021-11-17T18:49:52.479Z: + limactl shell --workdir=. 0 sudo /sbin/rc-service --ifnotstarted k3s start
```

**Comment by mook-as** [comment]
Thanks, fixed that in 89b9335 — need to write that file as executable on lima.

**Review by mattfarina — CHANGES_REQUESTED** [review]
The version downloaded needs to be updated. On startup RD can't find distro-0.8.tar because 0.7 was downloaded instead.

See https://github.com/rancher-sandbox/rancher-desktop/blob/43ba875d44b0474753d99da063ccdc92e40b8584/scripts/download/wsl.mjs#L11

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
