### PR TITLE
Use symlink to shorten Lima config path

### LINKED ISSUE #797: "Starting virtual machine" step fails due to SSH socket path being too long.
Rancher Desktop shows the "Starting virtual machine" until timeout. 

`~/Library/Application\ Support/rancher-desktop/lima/0/ha.stderr.log` contains the following lines:

```json
{"level":"debug","msg":"stdout=\"\", stderr=\"unix_listener: path \\\"/Users/od.andreas.zitzelsberger/Library/Application Support/rancher-desktop/lima/0/ssh.sock.Rcl2KoI2X03Sbknt\\\" too long for Unix domain socket\\r\\n\", err=failed to execute script \"ssh\": stdout=\"\", stderr=\"unix_listener: path \\\"/Users/XXXXXXXXXXXXXXXXXXXXXXXX/Library/Application Support/rancher-desktop/lima/0/ssh.sock.Rcl2KoI2X03Sbknt\\\" too long for Unix domain socket\\r\\n\": exit status 255","time":"2021-10-14T15:28:04+02:00"}
```

with `XXXXXXXXXXXXXXXXXXXXXXXX` being my user name. Please note that the path `/Users/XXXXXXXXXXXXXXXXXXXXXXXX/Library/Application Support/rancher-desktop/lima/0/ssh.sock.Rcl2KoI2X03Sbknt` has 109 characters. The path length for Unix Domain Sockets is limited to 108 characters (Linux) or 104 characters (Mac). Unfortunately, my user name is managed and cannot be changed. While the user name is long, I believe it's length is not uncommon. 

**To Reproduce**
* Start Rancher Desktop on a Mac with a user name that has 21 characters or more.

**Result**
Rancher Desktop shows the "Starting virtual machine" until timeout. 

**Expected behaviour**
Rancher Desktop starts up properly.

**Screenshots**
grafik

**Setup (please complete the following information):**
- macOS  11.6
 - Rancher Desktop 0.6.0
 - Kubernetes 1.21.5

### PR DESCRIPTION
**Pull request by jsoref**
Fixes #797

### CODE REVIEW

**Review by mook-as — CHANGES_REQUESTED** [review]
This wouldn't actually solve the issue, as we're running [`limactl start`](https://github.com/rancher-sandbox/rancher-desktop/blob/c0db99c3b85efcfb471c5d8b78164cc2072116c2/src/k8s-engine/lima.ts#L1259) with the long path (and that's the one emitting the failure).

We _will_ need to fix the nerdctl stub too, of course (because that also spawns limactl), but this isn't the full thing.

**Review by ericpromislow — CHANGES_REQUESTED** [review]
This kind of setup should be done as soon as the directory is either created or known to exist. The problem with this solution is that we're going to run the same code every time someone runs `nerdctl`. 

So setting up the symlink after `LAS/rd/lima` is first created should happen at https://github.com/rancher-sandbox/rancher-desktop/blob/e17f9308309a84191a7cbbb4847c1796796dfffb/src/k8s-engine/lima.ts#L582 .

Creating a symlink when the `LAS/rd/lima` already exists could actually be done on upgrades only by leveraging the settings update table at https://github.com/rancher-sandbox/rancher-desktop/blob/e17f9308309a84191a7cbbb4847c1796796dfffb/src/config/settings.ts#L21 and adding a setting for `4:` at https://github.com/rancher-sandbox/rancher-desktop/blob/e17f9308309a84191a7cbbb4847c1796796dfffb/src/config/settings.ts#L255 . If we don't want to overload the settings module with non-settings stuff we could just check for an existing symlink in the `else` part of the above code.

Or did I miss something?

**Comment by jandubois** [comment]
There are a number of issues to think through:

* what is the name we want to create? Is `~/.lima-rd` the right one (it doesn't tab-complete when you already have `~/.lima`)?
* what do we do when both `~/Library/Application\ Support/rancher-desktop/lima` and `~/.lima-rd` exist?
* how do we migrate an existing install from the current name to the symlink setup
* how does this affect the code excluding the directory from time machine backups?
* should the symlink always be created, or only when necessary?

I'm tempted to move this discussion into a new issue, as this should be hashed out before coding starts... 😄

**Comment by jandubois** [comment]
Please move discussion to #1465

**Comment by mook-as** [comment]
Closing this PR — this needs to be done in the TypeScript code (and will probably more discussion before we can agree on the details of the implementation).

Thanks for getting this rolling!

**Pull request closed without merging**
