### PR TITLE
Fix tray context menu immediately closing when window is not focused

### PR DESCRIPTION
**Pull request by rak-phillip**
This fixes an issue where the tray context menu would immediately close if the rancher desktop window did not have focus by updating our version of electron.

#575

Signed-off-by: Phillip Rak <phillip.rak@suse.com>

### CODE REVIEW

**Comment by rak-phillip** [comment]
The behavior I was experiencing seems to be an issue with our version of electron, but I'm not seeing much of a mention of it in the [changelog](https://www.electronjs.org/releases/stable?version=12). I was unable to replicate the behavior after standing up a new project. After deciding to change our electron version, the issue was fixed. Reverting back to the original version and the behavior came back..

**Review by mook-as — APPROVED** [review]
LGTM:
- The tray icon thing is fixed.
- Upgrades still work, which is the only thing I'm worried about breaking.

**Comment by rak-phillip** [comment]
@mook-as I updated my npm version to reduce `package-lock` churn for this PR as well

**Review by mook-as — APPROVED** [review]
Thanks! I totally missed that in this PR, somehow :)

**Pull request merged**
