### PR TITLE
nerdctl-stub: regenerate for 2.0.1

### PR DESCRIPTION
**Pull request by mook-as**
Reviewing ignoring whitespace is recommended.  None of the affected flags appear to have to do with file paths (but please double check if possible).

Regenerated with `yarn generate:nerdctl-stub` on Windows.

### CODE REVIEW

**Comment by jandubois** [comment]
Looks like we forgot to update the stub for the 2.0.0 release.

> None of the affected flags appear to have to do with file paths

The `--build-context` option takes a list of `name=value` pairs. If the `value` doesn't start with a URI scheme, then it is a local filename. See https://github.com/containerd/nerdctl/blob/c0b8f632d6555796f710c4e7219fe4d75e916d7d/pkg/cmd/builder/build.go#L292-L322 for how it is parsed.

**Review by jandubois — CHANGES_REQUESTED** [review]
The `--build-proxy` arguments may contain filenames, so probably need special handling.

Everything else seems fine.

**Comment by mook-as** [comment]
PR updated with `--build-context` implementation.  I couldn't find a `--build-proxy` argument, and `--sig-proxy` seems to be a bool.

**Comment by jandubois** [comment]
> PR updated with `--build-context` implementation. I couldn't find a `--build-proxy` argument, and `--sig-proxy` seems to be a bool.

Oh, sorry, that was my typo; it was supposed to be `--build-context`.

**Review by jandubois — CHANGES_REQUESTED** [review]
`nerdctl build` no longer works on Windows, even without `--build-context`. Fails on both Win32 and WSL with

```
$ nerdctl build .
FATA[0000] lstat /Containerfile: no such file or directory
```

**Comment by jandubois** [comment]
```console
PS C:\Users\SUSE\hello> nerdctl build -f c:\users\suse\hello\Dockerfile .
FATA[0000] lstat /c:\users\suse\hello\Dockerfile: no such file or directory
PS C:\Users\SUSE\hello> nerdctl build -f Dockerfile .
FATA[0000] lstat /Containerfile: no such file or directory
PS C:\Users\SUSE\hello> nerdctl build -f .\Dockerfile .
FATA[0000] lstat /.\Dockerfile: no such file or directory
```

**Comment by jandubois** [comment]
So this one works:

```
PS C:\Users\SUSE\hello> nerdctl build --file c:\users\suse\hello\Dockerfile .
[+] Building 2.8s (8/8)
```

It looks like the `builder build -f` setting is missing in the config.

**Comment by jandubois** [comment]
`build -f` works now, but still doesn't default to `Dockerfile`:

```
PS C:\Users\SUSE\hello> nerdctl build -t hello .
FATA[0000] lstat /Containerfile: no such file or directory
PS C:\Users\SUSE\hello> nerdctl build -t hello -f Dockerfile .
[+] Building 2.7s (8/8)
```

`--build-context` does not seem to work:

```
PS C:\Users\SUSE\hello> nerdctl build -t hello -f Dockerfile --build-context "alpine:3.20=c:\user\suse\buildctx" .
The parameter is incorrect.
Error code: Wsl/Service/E_INVALIDARG
```

**Review by mook-as — COMMENTED** [review]
Jan's changes LGTM

**Review by jandubois — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
