### PR TITLE
screenshots, mock data

### PR DESCRIPTION
**Pull request by torchiaf**
Fixes: #3430

- fix version in General page.
- fix Diagnostics page to show mock checks

Signed-off-by: Francesco Torchia <francesco.torchia@suse.com>

### CODE REVIEW

**Review by rak-phillip — CHANGES_REQUESTED** [review]
It looks like there might be something wrong. `npm run screenshots` consistently produces a failure

```
  ✓  1 screenshots.e2e.spec.ts:52:3 › Main App Test › Main Page (2s)
  ✘  2 screenshots.e2e.spec.ts:75:3 › Main App Test › Preferences Page (4s)
Skipping packaging logs, not running in Cirrus CI


  1) screenshots.e2e.spec.ts:75:3 › Main App Test › Preferences Page ===============================

    locator.click: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "[data-test="diagnostics-mute-row-MOCK_CHECKER"]"
    ============================================================

      67 |     // show diagnostics badge
      68 |     await page.waitForTimeout(200);
    > 69 |     diagnosticsPage.checkerRows('MOCK_CHECKER').muteButton.click();
         |                                                            ^
      70 |     await page.waitForTimeout(200);
      71 |
      72 |     await screenshot.take('Diagnostics');

        at /home/phillip/Development/rancher-desktop-pr/screenshots/screenshots.e2e.spec.ts:69:60


  1 failed
    screenshots.e2e.spec.ts:75:3 › Main App Test › Preferences Page ================================
  1 passed (1m)
```

**Comment by torchiaf** [comment]
> It looks like there might be something wrong. `npm run screenshots` consistently produces a failure
> 
> ```
>   ✓  1 screenshots.e2e.spec.ts:52:3 › Main App Test › Main Page (2s)
>   ✘  2 screenshots.e2e.spec.ts:75:3 › Main App Test › Preferences Page (4s)
> Skipping packaging logs, not running in Cirrus CI
> 
> 
>   1) screenshots.e2e.spec.ts:75:3 › Main App Test › Preferences Page ===============================
> 
>     locator.click: Timeout 30000ms exceeded.
>     =========================== logs ===========================
>     waiting for selector "[data-test="diagnostics-mute-row-MOCK_CHECKER"]"
>     ============================================================
> 
>       67 |     // show diagnostics badge
>       68 |     await page.waitForTimeout(200);
>     > 69 |     diagnosticsPage.checkerRows('MOCK_CHECKER').muteButton.click();
>          |                                                            ^
>       70 |     await page.waitForTimeout(200);
>       71 |
>       72 |     await screenshot.take('Diagnostics');
> 
>         at /home/phillip/Development/rancher-desktop-pr/screenshots/screenshots.e2e.spec.ts:69:60
> 
> 
>   1 failed
>     screenshots.e2e.spec.ts:75:3 › Main App Test › Preferences Page ================================
>   1 passed (1m)
> ```

Hi Phil , thanks for the review. 
I cannot reproduce the bug in my environment. Are you using Linux?
I pushed a new commit to improve the navigation to Diagnostics tab, but I am not really sure the bug depends on the timeout.
It seems that in your case, the task is not able to navigate to Diagnostics page, this would explain why the selector `data-test="diagnostics-mute-row-MOCK_CHECKER"` is not found.
Could you please give it a new try with last change?

**Review by adamkpickering — APPROVED** [review]
LGTM.

**Review by rak-phillip — DISMISSED** [review]
@torchiaf thanks for the explanation, what you describe definitely makes sense. 

The changes look good to me. It looks like there's a conflict that needs resolving before this can merge.

**Comment by torchiaf** [comment]
Rebased

**Review by rak-phillip — APPROVED** [review]
LGTM

**Pull request merged**
