### PR TITLE
Allow for weird result for `docker-credentials-pass`.

### PR DESCRIPTION
**Pull request by ericpromislow**
Add a change that will let the credential `e2e` tests pass when using `docker-credential-pass`

### CODE REVIEW

**Review by mook-as — CHANGES_REQUESTED** [review]
Shouldn't we be overriding the credential store during the test to use something that produces static results? We should not be mutating the system credentials.

**Comment by ericpromislow** [comment]
The problem is that we do set `credsStore` to one of `%w/osxkeychain wincred pass secretservice` at startup. So this change just allows for expected results when using `pass`.

**Comment by ericpromislow** [comment]
This PR should die once we implement `docker-credential-X` (where X is something like `default` or `none`) and use that in our CI

**Comment by ericpromislow** [comment]
No need for this PR now that we have docker-credentials-none

**Pull request closed without merging**
