### PR TITLE
Escaped Html character in the snapshot creation dialog box

### PR DESCRIPTION
**Pull request by VikalpRusia**
## Changes
Escape the snapshot name in create snapshot dialog

## Why?
Causing unintended interaction with the UI elements.

## How
Escape the name of the created snapshot in the dialog displayed to avoid interpreting it as HTML.

### Details
Referring to this comment -
Issue: https://github.com/rancher-sandbox/rancher-desktop/pull/7542#issuecomment-2375338228

### Changes
- reused the escapeHtml function in utils/string file

## Screenshots
Screenshot 2024-09-26 at 9 45 51 AM

### CODE REVIEW

**Comment by VikalpRusia** [comment]
@mook-as - please review the PR

**Comment by jandubois** [comment]
> @mook-as - please review the PR

@VikalpRusia Please use the GitHub mechanism to request a review instead of adding a comment:

CleanShot 2024-09-26 at 10 44 26@2x

That way the request shows up properly in that person's review queue at https://github.com/pulls/review-requested

**Comment by VikalpRusia** [comment]
> > @mook-as - please review the PR
> 
> @VikalpRusia Please use the GitHub mechanism to request a review instead of adding a comment:
> 
> CleanShot 2024-09-26 at 10 44 26@2x
> 
> That way the request shows up properly in that person's review queue at https://github.com/pulls/review-requested

Hi @jandubois 

I wanted to do this but can't add somebody there - no settings icon

Screenshot 2024-09-26 at 11 18 14 PM

**Comment by jandubois** [comment]
> I wanted to do this but can't add somebody there - no settings icon

I'm sorry, my bad. I didn't realize you need write access to the repository to request a reviewer.

**Comment by mook-as** [comment]
On the upside, I subscribe to the repository (so I'd have seen your PR without the ping), and at a minimum we go through the PR list every workday so we'd have seen it even if that failed.  So the ping isn't necessary :)

**Review by mook-as — APPROVED** [review]

**Review by mook-as — APPROVED** [review]

**Pull request merged**
