### PR TITLE
Test presence/absence of apphome/snapshots.

### LINKED ISSUE #5423: Add a bats test for factory-reset when snapshots are present

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #5423

### CODE REVIEW

**Comment by jandubois** [comment]
I want to postpone reviewing the PR until #5378 and #5419 have been resolved because they will change the way `PATH_APP_HOME` is set and used.

**Comment by jandubois** [comment]
> I want to postpone reviewing the PR until #5378 and #5419 have been resolved

Turning into draft mode until the prerequisite issues are closed.

**Comment by ericpromislow** [comment]
There are currently no bats tests that exercise the preservation and deletion of the snapshots directory after a factory-reset.

**Review by jandubois — APPROVED** [review]
I still think these tests belong together with the rest of the factory-reset tests, but we can always refactor later.

**Pull request merged**
