### PR TITLE
Allow doc version to be `1.9-tech-preview`

### PR DESCRIPTION
**Pull request by jandubois**
For testing download a build from https://github.com/rancher-sandbox/rancher-desktop/actions/runs/4691378070 and verify that the docs links go to `1.9-test-release2` and not `next`.

### CODE REVIEW

**Comment by jandubois** [comment]
Seems to work for at least the pre-release versions. The help button in the Preferences tried to open https://docs.rancherdesktop.io/1.9-test-release-2/ui/preferences/application#general, which is exactly what I expected.

**Review by rak-phillip — APPROVED** [review]
LGTM - help links navigate to `https://docs.rancherdesktop.io/1.9-test-release-2/...`

**Comment by sunilarjun** [comment]
Not able to run the download as my mac security settings are not allowing it to run and I can't change my settings it seems, however, testing was successful with the docs site having the version named `1.9-tech-preview`. With Phil's comment above, I think this can be merged in. Thanks!

**Comment by jandubois** [comment]
> Not able to run the download as my mac security settings are not allowing it to run and I can't change my settings it seems,

@sunilarjun You have to run the following command to remove the quarantine attributes after installing a CI build before you can run it:

```shell
xattr -dr com.apple.quarantine /Applications/Rancher\ Desktop.app/
```

**Pull request merged**
