### PR TITLE
Delay starting the server API until the config has been loaded.

### LINKED ISSUE #5099: settings API may return "undefined"
For a short period of time, after the API starts responding, it returns an undefined settings object:

```console
$ rdctl api /settings
undefined
$ echo $?
0
```

I think the server side should return an error when settings are not yet available. Alternatively, the socket should not be listening until the app is ready to respond.

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #5099

### CODE REVIEW

**Review by mook-as — CHANGES_REQUESTED** [review]
Per Slack discussion, we're leaning towards changing things so the HTTP server only starts after the settings have completed loading (with all the checks) instead.

**Comment by ericpromislow** [comment]
Running this command while starting up RD:
```bash
while : ; do
  echo list-settings
  ./resources/darwin/bin/rdctl list-settings
  echo $?
  sleep 0.1
  echo api settings
  ./resources/darwin/bin/rdctl api settings
  echo $?
  sleep 0.1
  echo put settings
  ./resources/darwin/bin/rdctl api /settings -X PUT -b '{"version": 9, "kubernetes": {"version": "moo"}}'
  echo $?
  sleep 0.1
  echo extension install
  ./resources/darwin/bin/rdctl extension install beeker
  echo $?
  sleep 0.1
done

```

I get this output, where the result `rdctl` sees goes immediately from `connection refused` to a working server.
```

list-settings
Error: Get "http://127.0.0.1:6107/v1/settings": dial tcp 127.0.0.1:6107: connect: connection refused
1
api settings
Error: Get "http://127.0.0.1:6107/v1/settings": dial tcp 127.0.0.1:6107: connect: connection refused
1
put settings
Error: Put "http://127.0.0.1:6107/v1/settings": dial tcp 127.0.0.1:6107: connect: connection refused
1
extension install
Error: Post "http://127.0.0.1:6107/v1/extensions/install?id=beeker": dial tcp 127.0.0.1:6107: connect: connection refused
1
list-settings
{
  "version": 9,
  "application": {
    "adminAccess": false,
    "debug": false,
    "extensions": {
…
```

**Review by mook-as — CHANGES_REQUESTED** [review]
The code looks fine, but there's a rebased copy of #5098 in the log. Please rebase on `main` and we can merge.

```
* 05eac06083e5382cc0301f1424e73f81b7826dc5 (pr/5104/head, origin/5099-flag-premature-requests) Verify that settings have been loaded before servicing API requests involving them.
* 4a1f4b104ba279c7bf2562988bd41e4f73dd77bb RDX: Expose API to main window
| * 120c0a1074063e427e47a440cdb7d332ef540efa (origin/main) Merge pull request #5098 from mook-as/extensions/expose-to-app
|/| 
| * df2a2f0ef11630755dc2d8f33bc7f5978b0b5064 (pr/5098/head, extensions/expose-to-app) RDX: Expose API to main window
* |   dc2a7b7a5a632c3386118c789af3798bf852c138 Merge pull request #5103 from jandubois/merge-1.9.1
```

**Comment by ericpromislow** [comment]
Done...

**Review by mook-as — APPROVED** [review]

**Pull request merged**
