### PR TITLE
Windows: Persist data on upgrades

### PR DESCRIPTION
**Pull request by mook-as**
This is the equivalent of #635 — this makes it so we don't need to wipe everything when we upgrade WSL distro versions.

/cc @mattfarina

### CODE REVIEW

**Comment by mook-as** [comment]
Sorry, it looks like upgrading from 0.4.1 is broken (due to the differences in the old distro); going to try to fix that first.

**Comment by mattfarina** [comment]
I just took this for a spin (have not done a code review yet) and discovered:
- The "Reset Kubernetes" button doesn't work. The workloads stay around.
- The "Reset Kubernetes and Containers" button doesn't work either. The workloads and images stick around
- The "Factor Reset" button doesn't work either. It removes the _rancher-desktop_ WSL instance but not the data instance.
- When I checked out the PR and ran `npm run dev` the upgrade worked as I would have expected. But, when I pulled down the package for Windows and went through the upgrade process (cleared config, installed 0.4.1, installed a workload [wordpress], then upgraded to this) it failed. Note, when I did an `npm run dev` that same workload was running and it was an upgrade. The wsl.log file noted:
  ```
  Creating initial data distribution...
  WSL failed to execute busybox test -e /lib
  tar: removing leading '/' from member names
  tar: /var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/76/fs/opt/bitnami/mariadb/tmp/mysql.sock: socket ignored
  ```

**Comment by ericpromislow** [comment]
I installed the 0.4.1 release and couldn't upgrade to the github-built package of this PR (commit labeled "exclude files that don't exist").  Here's my procedure:

1. Start up the app, push an app, and verify I can see the app.  `kim images` isn't able to connect, but I can see k8s
2. Uninstall 0.4.1
3. Pull down the build for this PR 
4. Unzip and install
5. Accept the reboot as part of install
6. Now running RD 0.4.1-210-gc80224d
7. The main screen says there's an update available, and to restart the app. I'd prefer a button, but I flash the app.
8. Not much feedback that an update is in progress. The desktop icon sort of blinks (goes to a generic icon, and then back to the RD icon), but not much is happening.
9. After about a minute a dock RD icon starts blinking -- clicking it brings up the RD window running version 0.4.1 -- I'm confused. Why did it "upgrade" from a later version back to 0.4.1

Meanwhile, with this version, I get an error starting k8s -- code 1 this time (not code `(uint32) -1`), with this log in update.log:

```
Update is cached; forcing re-check to install.
Checking for update
Error reading update cache: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at xt.checkForUpdates (C:\Users\eric\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:2:118529)
    at async xt.getLatestVersion (C:\Users\eric\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:2:120099)
    at async Tt.getUpdateInfoAndProvider (C:\Users\eric\AppData\Local\Programs\Rancher Desktop\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:289:19)
    at async Tt.getUpdateInfoAndProvider (C:\Users\eric\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:2:120820)
    at async Tt.doCheckForUpdates (C:\Users\eric\AppData\Local\Programs\Rancher Desktop\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:303:24)
```

All uses of JSON really should be guarded with a catch that can at least give the name of the problematic file.

**Comment by mook-as** [comment]
Please don't use the in-app update from development builds; as far as concerned, `0.4.1-210-gc80224d` is a pre-release (instead of `alpha`, it's `210-gc80224d`) and is less than `0.4.1`.

The JSON issue is probably from updates and should be a separate issue, unrelated to this one.

**Comment by ericpromislow** [comment]
> Please don't use the in-app update from development builds; as far as concerned, `0.4.1-210-gc80224d` is a pre-release (instead of `alpha`, it's `210-gc80224d`) and is less than `0.4.1`.

I didn't want to upgrade, but shutting down the app and restarting it triggered the automatic update. Is there a way to avoid updating?

**Comment by mattfarina** [comment]
> I didn't want to "upgrade", but shutting down the app and restarting it triggered the automatic update. Is there a way to avoid updating?

On the main prefs screen there is a checkbox for the updates. Uncheck it.

If the updates dialog pops up, close it without clicking ok. That will skip applying the update.

**Comment by mook-as** [comment]
> Got another error when moving from the 0.4.0 release (not uninstalled) to this PR's `npm run dev`:
> 
> ```
> Error moving WSL distribution: fatal: Error: EBUSY: resource busy or locked, rename 'C:\Users\eric\AppData\Local\xdg.state\rancher-desktop\distro\ext4.vhdx' -> 'C:\Users\eric\AppData\Local\rancher-desktop\distro\ext4.vhdx'
> ```

That's from #547 and is fine; just means we don't end up moving the WSL distro (because the WSL VM is running, and still has the disk locked even though the rancher-desktop distribution is not running).  We'll just try again next time.

It's also completely irrelevant to this PR…

**Comment by ericpromislow** [comment]
I now get a k8s-failure, with this message in wsl.log:
```
The system cannot find the file specified.
```

Going to reboot to try to get around the locked vhdx problem.

**Comment by ericpromislow** [comment]
Got this to work by clearing everything, installing 0.4.1, pulling an image and pushing some pods, and then shutting down RD and leaving the WSL windows and running `npm run dev` on this PR --- everything came back up.

**Review by ericpromislow — APPROVED** [review]
Got it to work.

**Comment by ericpromislow** [comment]
In response to Matt's comment from yesterday:
> The "Reset Kubernetes" button doesn't work. The workloads stay around.
When I ran it, the workloads and non-system images were removed

> The "Reset Kubernetes and Containers" button doesn't work either. The workloads and images stick around
What does this button mean by "Containers"?  I pulled down the `Ruby` image before running Reset, and after it was gone.

This was with `npm run dev`.  Will try the package build next.

**Pull request merged**
