### PR TITLE
Bundle Lima

### LINKED ISSUE #379: Bundle lima and qemu with Rancher Desktop.app
Lima and qemu executables, libraries, and datafiles have been [extracted](https://github.com/AkihiroSuda/lima/blob/master/hack/lima-and-qemu.pl) from `/usr/local` into a relocatable tree. It can be downloaded from https://github.com/rancher-sandbox/lima/releases/download/rd-v0.1.0/lima-and-qemu.tar.gz

The files from the tarball should be included inside the `Rancher Desktop.app`, e.g. as `resources/darwin/lima`.

To run lima, the `resources/darwin/lima/bin`  directory must be added to the front of the `PATH`.

Lima installs all `~/.ssh/*.pub` files as authorized keys into the VM and will not work if there aren't any keys.

The [alpine](https://github.com/AkihiroSuda/lima/blob/master/examples/alpine.yaml) config file should be used as a basis for creating the RD VM (but bundle the ISO locally instead of loading it from github).

```
limactl start --tty=false alpine.yaml
limactl shell alpine uname
limactl stop alpine
limactl delete alpine
```

The lima instances are stored under `~/.lima`, which can be overridden via `LIMA_HOME`.

### PR DESCRIPTION
**Pull request by mook-as**
This adds Lima to `resources/darwin/lima` on macOS; note that we're not doing anything with it yet.

Fixes #379.

### CODE REVIEW

**Comment by jandubois** [comment]
I would have expected you to also bundle the ISO: https://github.com/rancher-sandbox/alpine-lima/releases/download/v0.0.1/alpine-lima-ci-3.13.5-x86_64.iso

Admittedly this request was done somewhat obscurely in #379:

>The [alpine](https://github.com/AkihiroSuda/lima/blob/master/examples/alpine.yaml) config file should be used as a basis for creating the RD VM (but bundle the ISO locally instead of loading it from github).

**Comment by mook-as** [comment]
Updated to bundle the ISO too.

I assume the path will be generated at run time (because we wouldn't know the correct path until then).

**Comment by jandubois** [comment]
> I assume the path will be generated at run time (because we wouldn't know the correct path until then).

That matches my assumption. 😄 

I expect us to write the config file when we start up a fresh VM:

* We can check with `limactl ls` if the VM already exists, and simply `limactl start rancher-desktop` when it is stopped.
* When it doesn't exist, we create the `rancher-desktop.yaml` config file (with the link to the ISO) and start/create the VM with `limactl start --tty=false /path/to/rancher-desktop.yaml`

**Review by mattfarina — APPROVED** [review]

**Comment by mattfarina** [comment]
@mook-as can you please fix the conflict

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
