### PR TITLE
Download docker-credential-osxkeychain 0.6.4 until it's fixed.

### LINKED ISSUE #3172: Temporarily drop back to docker-credentials-osxkeychain 0.6.4
### Actual Behavior

See #3171 -- that requires hearing from upstream.

In the meantime let's just move the mac version back to 0.6.4

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #3172

Signed-off-by: Eric Promislow <epromislow@suse.com>

### CODE REVIEW

**Comment by jandubois** [comment]
I would prefer to just revert #3110 until this issue is fixed and just create an issue to revert the revert again in the future.

**Comment by ericpromislow** [comment]
Well, 0.7.0 fixes the issue with `docker-credential-pass` that it wasn't failing when trying to lookup a non-existent ServerURL

**Comment by jandubois** [comment]
> Well, 0.7.0 fixes the issue with `docker-credential-pass` that it wasn't failing when trying to lookup a non-existent ServerURL

Ok, but that is only an issue for the test suite and not for users (they would still not be able to pull from a non-existent registry anyways).

If at all possible I don't want to ship different versions of supporting utilities on different platforms. It would be different if they were not shipped as part of the same release on a single repo.

**Comment by ericpromislow** [comment]
We've moved back to 0.6.4, will return to a later version once d-c-osxkeychain is fixed (or someone can explain why it doesn't work on my machine).

**Pull request closed without merging**
