### PR TITLE
Assorted BATS fixes for Windows

### PR DESCRIPTION
**Pull request by jandubois**

### CODE REVIEW

**Comment by ericpromislow** [comment]
Summary of failures:

```
platform.bats
 ✗ deploy s390x container
    in test file bats/tests/containers/platform.bats, line 62)
     `check_uname s390x s390x' failed

   -- output differs --
   expected (1 lines):
     s390x
   actual (2 lines):
     time="2023-07-13T22:30:04Z" level=warning msg="Platform \"linux/s390x\" seems incompatible with the host platform \"linux/amd64\". If you see \"exec format error\", see https://github.com/containerd/nerdctl/blob/main/docs/multi-platform.md"
     s390x
   --
```

On linux I just see `s390x`, but it looks like on Windows there's a warning line. Didn't investigate.

I'll write up each failure in a separate box to avoid making them too large.

**Comment by ericpromislow** [comment]
switch-engines.bats

-- There were errors at
```
✗ switch to containerd 
✗ switch back to containerd and verify containers
```

but apparently these are expected

**Comment by ericpromislow** [comment]
```
k8s/enable-disable-k8s

 ✗ re-enable kubernetes
   (from function `rdctl' in file bats/tests/helpers/commands.bash, line 72,
    in test file bats/tests/k8s/enable-disable-k8s.bats, line 27)
     `rdctl set --kubernetes-enabled=true' failed
   Error: Put "http://127.0.0.1:6107/v1/settings": dial tcp 127.0.0.1:6107: connectex: No connection could be made because the target machine actively refused it.
```

**Comment by ericpromislow** [comment]
```
 preferences/list-settings-output
✗ generates registry output
 -- output does not contain substring --
   substring (1 lines):
     "pathManagementStrategy"="rcfiles"
...
  "pathManagementStrategy"="manual"
```

**Comment by ericpromislow** [comment]
`   ===== registry/creds =====` all tests fail with these error messages:
```
   (from function `local_setup' in file bats/tests/registry/creds.bats, line 21,
    from function `call_local_function' in file bats/tests/registry/../helpers/load.bash, line 68,
    from function `setup' in test file bats/tests/registry/../helpers/load.bash, line 98)
     `call_local_function' failed
   wslpath: /mnt/c/Users/eric/AppData/Local/Temp/auth: No such file or directory
   wslpath: /mnt/c/Users/eric/AppData/Local/Temp/certs: No such file or directory
   mkdir: cannot create directory ‘’: No such file or directory
```

**Review by ericpromislow — CHANGES_REQUESTED** [review]
See failures in comments.

**Comment by jandubois** [comment]
@ericpromislow PTAL

With this PR only the `switch-engines` and `traefik` tests are known to fail, even when testing with `containerd`.

**Comment by ericpromislow** [comment]
I'm still seeing https://github.com/rancher-sandbox/rancher-desktop/pull/5160#issuecomment-1635056011 -- this is using the Windows 1.9.1 release in user-mode, and the latest change on this branch

**Comment by ericpromislow** [comment]
Same failure on k8s/enable-disable-k8s (again against the 1.9.1 release installed for me only)

**Comment by ericpromislow** [comment]
My command-line:
```
RD_LOCATION=user RD_USE_WINDOWS_EXE=true bats/bats-core/bin/bats bats/tests/containers/platform.bats bats/tests/containers/switch-engines.bats  bats/tests/k8s/enable-disable-k8s.bats  bats/tests/preferences/list-settings-output.bats  bats/tests/registry/creds.bats
```

Only `preferences/list-settings-output.bats` passed this time. Everything else failed with the same error messages as in the previous run.

This was using this branch in a WSL session, with a 1.9.1 release installed for user only in Windows

**Review by ericpromislow — CHANGES_REQUESTED** [review]
Some tests still fail. See my recent comments (2023-07-19 around 12 noon PDT)

**Comment by ericpromislow** [comment]
Update using a newer CI build for RD fixed `containers/platforms.bats.

The `registry/creds.bats` needs to do `mkdir -p "$AUTH_DIR"` and `mkdir -p "$CERTS_DIR"` and not the `..._VOLUME` variants. With that change, they passed.

Still failing:
```
containers/switch-engines.bats
k8s/enable-disable-k8s.bats
```
and I didn't run the traefik test which is known to fail

**Review by ericpromislow — APPROVED** [review]
The two tests that are known to fail are still failing, and I saw a few network-related flakes. Approving so we can get these changes into `main` and make it easier to run win bats tests.

**Pull request merged**
