### PR TITLE
Update screenshots as we added new tabs in Preferences modal

### LINKED ISSUE #4632: Update screenshots script for Preferences dialog changes

### PR DESCRIPTION
**Pull request by torchiaf**
Signed-off-by: Francesco Torchia <francesco.torchia@suse.com>

Fixes #4632

### CODE REVIEW

**Review by rak-phillip — CHANGES_REQUESTED** [review]
Looks good to me, just one small change before we merge.

**Comment by rak-phillip** [comment]
Rerunning failed CI steps

**Comment by torchiaf** [comment]
> Rerunning failed CI steps

There was unrelated issues in the CI. Running again the jobs, let's see.

**Review by rak-phillip — APPROVED** [review]
LGTM

**Pull request merged**
