### PR TITLE
Run gofmt -d on lint:nofix

### PR DESCRIPTION
**Pull request by ericpromislow**
Signed-off-by: Eric Promislow <epromislow@suse.com>

### CODE REVIEW

**Review by mook-as — CHANGES_REQUESTED** [review]
On Windows:
```
$P$G> npm run lint:nofix

> rancher-desktop@1.2.0 lint:nofix
> eslint --ignore-path=.gitignore --ext mjs,js,ts,vue .; gofmt -d src/go

Invalid option '-d' - perhaps you meant '-c'?
```
(You probably need `&&` like the other things)

**Comment by ericpromislow** [comment]
Didn't think about Windows - I wanted to run `gofmt` even if there are lint problems in the `js`.

And `gofmt -h` shows `-d	display diffs instead of rewriting files` on all three platforms. The invalid option part comes from the `;` acting as an ordinary arg on windows, and that message came from `eslint`, not `gofmt`. If every cmd-line utility put an ID prefix at the start of every line, the error would have been clearer, but that will never happen.

**Comment by ericpromislow** [comment]
Now in powershell `&&` isn't the same as in `*sh` -- isn't it the same as `!$` on `*sh`? How is `npm t` working on Windows then? And if something is handling `&&` statement separators on Windows, why not handle `;` as well?

**Comment by mook-as** [comment]
Digging through way too much code:
- npm runs scripts with [`cmd`](https://github.com/npm/run-script/blob/16eb42a76cb9732c6e2250a40fd0574a965d3bec/lib/make-spawn-args.js#L11)
- `cmd` [supports `&&`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmd#remarks)

**Review by mook-as — APPROVED** [review]
That should work.
(It doesn't work for me because I don't have a `diff.exe` on my path; but I can live with that.)

**Pull request merged**
