### PR TITLE
Bump to lima 0.6.0 plus lima PR#149

### LINKED ISSUE #471: Create a lima-and-qemu release containing lima#149
[Verify that the process specified in a PID file is still running](https://github.com/lima-vm/lima/pull/149)

Create release via Github Actions on the [lima-and-qemu](https://github.com/rancher-sandbox/lima-and-qemu) repo.

Use independent version number for the releases to address https://github.com/rancher-sandbox/rancher-desktop/pull/430#discussion_r683196851.

### PR DESCRIPTION
**Pull request by jandubois**
Note that I've only built the `lima-and-qemu-v1.0` release (via GHA); I have not actually tested the new binaries with Rancher Desktop.

Closes #471

### CODE REVIEW

**Comment by mook-as** [comment]
I can't seem to login:
- lima is stuck on `[hostagent] Waiting for the essential requirement 1 of 4: \"ssh\"`
- Trying to login via `socat stdin unix:…/serial.sock` gives:
```
lima-rancher-desktop login: root
root
login: PAM Failu
lima-rancher-desktop login: 
```
(Yes, `PAM Failure` is missing two characters.)

It could be something I'm doing wrong locally, but it's… difficult to test :)

**Comment by jandubois** [comment]
I cannot repro:

```console
$ limactl start --tty=false ~/Library/State/rancher-desktop/lima/rancher-desktop/lima.yaml
INFO[0000] Terminal is not available, proceeding without opening an editor
INFO[0000] Attempting to download the image from "/Volumes/ThunderBlade/suse/rd/resources/darwin/alpline-lima-v0.1.0-std-3.13.5.iso"
INFO[0000] Downloaded image from "/Volumes/ThunderBlade/suse/rd/resources/darwin/alpline-lima-v0.1.0-std-3.13.5.iso"
INFO[0000] [hostagent] Starting QEMU (hint: to watch the boot progress, see "/Users/jan/.lima/lima/serial.log")
INFO[0000] SSH Local Port: 60020
INFO[0000] [hostagent] Waiting for the essential requirement 1 of 4: "ssh"
INFO[0018] [hostagent] The essential requirement 1 of 4 is satisfied
INFO[0018] [hostagent] Waiting for the essential requirement 2 of 4: "sshfs binary to be installed"
INFO[0019] [hostagent] The essential requirement 2 of 4 is satisfied
INFO[0019] [hostagent] Waiting for the essential requirement 3 of 4: "/etc/fuse.conf to contain \"user_allow_other\""
INFO[0019] [hostagent] The essential requirement 3 of 4 is satisfied
INFO[0019] [hostagent] Waiting for the essential requirement 4 of 4: "the guest agent to be running"
INFO[0019] [hostagent] The essential requirement 4 of 4 is satisfied
INFO[0019] [hostagent] Mounting "/Users/jan/Library/Caches/rancher-desktop/k3s"
INFO[0019] [hostagent] Forwarding "/run/user/501/lima-guestagent.sock" (guest) to "/Users/jan/.lima/lima/ga.sock" (host)
INFO[0019] READY. Run `limactl shell lima` to open the shell.
$ limactl shell lima
ash: cd: line 1: can't cd to /Users/jan/suse/rd: No such file or directory
lima-lima:/Users/jan$
```

Did you check `ha.stderr.log` and `serial.log` to see if there is anything interesting in there?

**Comment by mattfarina** [comment]
I can reproduce the issue @mook-as is seeing. The following is repeated in my logs...

```
time="2021-08-10T10:55:58-04:00" level=info msg="[hostagent] Waiting for the essential requirement 1 of 4: \"ssh\""
```

**Review by mook-as — APPROVED** [review]
I can no longer reproduce my issue… and it's the same checkout. 😕

**Comment by ericpromislow** [comment]
Same experience as reported by @mook-as  and @mattfarina  -- `limactl start rancher-desktop` is stuck on `essential requirement 1`

Seems like there's some state dependency here:

```
$ limactl rm lima
…
$ limactl rm rancher-desktop
…
$ limactl start --tty=false ~/Library/State/rancher-desktop/lima/rancher-desktop/lima.yaml
INFO[0000] Terminal is not available, proceeding without opening an editor
INFO[0000] Attempting to download the image from "/Users/ericp/workspace/rancher/desktop/resources/darwin/alpline-lima-v0.1.0-std-3.13.5.iso"
INFO[0000] Downloaded image from "/Users/ericp/workspace/rancher/desktop/resources/darwin/alpline-lima-v0.1.0-std-3.13.5.iso"
INFO[0000] [hostagent] Starting QEMU (hint: to watch the boot progress, see "/Users/ericp/.lima/lima/serial.log")
INFO[0000] SSH Local Port: 54806
INFO[0000] [hostagent] Waiting for the essential requirement 1 of 4: "ssh"
INFO[0000] [hostagent] QEMU has exited
FATA[0000] exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see "/Users/ericp/.lima/lima/ha.stderr.log")
```

The ha.stderr.log file has some permission-denied errors:

```
…
{"level":"debug","msg":"executing script \"ssh\"","time":"2021-08-10T10:35:54-07:00"}
…
{"level":"debug","msg":"stdout=\"\", stderr=\"ericp@127.0.0.1: Permission denied (publickey,password,keyboard-interactive).\\r\\n\", err=failed to execute script \"ssh\": stdout=\"\", stderr=\"ericp@127.0.0.1: Permission denied (publickey,password,keyboard-interactive).\\r\\n\": exit status 255","time":"2021-08-10T10:35:54-07:00"}
…
{"error":"exit status 1","level":"info","msg":"QEMU has exited","time":"2021-08-10T10:35:54-07:00"}
{"level":"debug","msg":"qemu[stderr]: Please use server=on instead","time":"2021-08-10T10:35:54-07:00"}
exit status 1
```

**Comment by jandubois** [comment]
I believe the issue is due to [Persist all of /etc on the data volume](https://github.com/lima-vm/lima/pull/143).

In the previous version we have persisted only `/etc/ssh` to the data volume. When that instance is started with the new lima, it will see that `/mnt/data/etc` exists and mount it over `/etc`, shadowing all the other content of the directory.

The "fix" is to delete the instance and start fresh. Since we never released RD based on lima, users should not have existing instances, so should never run into this.

**Comment by jandubois** [comment]
@ericpromislow @mattfarina Please confirm that resetting RD fixes the issue for you.

cc/ @AkihiroSuda Looks like I introduced a breaking change with persisting all of `/etc` instead of just `/etc/ssh`. Do you want me to add a workaround in Lima for this as well, or do we just hope that nobody has existing Alpine instances that they want to keep after moving to lima-v0.6.0?

**Comment by AkihiroSuda** [comment]
> do we just hope that nobody has existing Alpine instances that they want to keep after moving to lima-v0.6.0?

SGTM

**Comment by mattfarina** [comment]
I tested it after wiping my VM and it worked.

**Review by mattfarina — APPROVED** [review]

**Pull request merged**
