### PR TITLE
docker-credential-rancher-desktop should not show curl errors

### LINKED ISSUE #2613: nerdctl login throws curl output
### Actual Behavior

```
± nerdctl login
curl: (22) The requested URL returned error: 400
Enter Username: 
```

### Steps to Reproduce

1. start RD with containerd
2. nerdctl login

### Result

```
± nerdctl login
curl: (22) The requested URL returned error: 400
Enter Username: 
```

### Expected Behavior

```
± nerdctl login

Enter Username: 
```

### Additional Information

_No response_

### Rancher Desktop Version

1.4.1-562-g8d799160

### Rancher Desktop K8s Version

1.21.14

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Catalina

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

_No response_

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by jandubois**
But add an option to allow adding --show-error option for e2e tests.

Fixes #2613

### CODE REVIEW

**Review by ericpromislow — CHANGES_REQUESTED** [review]
I needed to make this change to get the e2e test to pass locally (on macOS):
```
diff --git a/e2e/credentials-server.e2e.spec.ts b/e2e/credentials-server.e2e.spec.ts
index 27f3f647..48632aa1 100644
--- a/e2e/credentials-server.e2e.spec.ts
+++ b/e2e/credentials-server.e2e.spec.ts
@@ -317,7 +317,8 @@ describeWithCreds('Credentials server', () => {
       'shell',
       'sh',
       '-c',
-      `SECRET=$(tr -dc 'A-Za-z0-9,._=' < /dev/urandom |  head -c5242880); \
+      `export CREDFWD_CURL_OPTS="--show-error";\
+       SECRET=$(tr -dc 'A-Za-z0-9,._=' < /dev/urandom |  head -c5242880); \
        echo '{"ServerURL":"https://example.com/v1","Username":"alice","Secret":"'$SECRET'"}' |
          /usr/local/bin/docker-credential-rancher-desktop store`
     ];
```

**Comment by jandubois** [comment]
> I needed to make this change to get the e2e test to pass locally (on macOS):

That change is already in the PR; I guess you were running the test with an earlier version of the PR (I did push updates twice).

**Comment by ericpromislow** [comment]
I think you still need my change -- the CI E2E tests are failing for the same reason.

**Review by ericpromislow — CHANGES_REQUESTED** [review]
CI still needs the `export CREDFWD_CURL_OPTS...` addition in the e2e test file.

**Comment by jandubois** [comment]
> CI still needs the `export CREDFWD_CURL_OPTS...` addition in the e2e test file.

Yeah, it was missing the `export` part, sorry! Fixed now, I hope.

**Review by ericpromislow — APPROVED** [review]
LGTM

**Pull request merged**
