### PR TITLE
On macOS, move the other config files into `~/Library/Preferences/rancher-desktop`

### LINKED ISSUE #5419: paths_linux.go: `AppHome` should be `filepath.Join(dataHome, appName)`
### Actual Behavior

it's too confusing with `AppHome:  filepath.Join(configHome, appName),`

On macOS, we're correct putting `settings.json` in `~/Library/Preferences/rancher-desktop`

On linux, `credential-server.json` and `rd-engine.json` should go in `~/.local/share/rancher-desktop`

and the factory-reset should delete them from the old location (which will happen if `rdctl factory-reset` deletes all of `~/.config/rancher-desktop`

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #5419

For some reason (probably that paths set `AppHome` to `~/L/Prefs/r-d` and not `~/L/AS/r-d`), on macOS, `rd-engine.json` and `credential-server.json` weren't put in the prefs directory.

Note that by bumping the settings version to 10, we can check for files in their legacy location just once, rather than every time in `rdctl/factory-reset`.

There's no need to move files from the legacy location to the new one, because their contents are reset every time Rancher Desktop starts up.

### CODE REVIEW

**Comment by jandubois** [comment]
I'm confused: this PR moves application data on macOS, but claims to fix #5419, which is about Linux.

This change for macOS is wrong; the `/Library/Preferences` folder should only be used to store user preferences and not for any other application data, which should go to `/Library/Application Support`. So the current locations for the data files are correct on macOS.

I have not yet verified if the claims of #5419 for Linux are correct, but I think the location of these files on Windows is wrong (see also #5378).

**Review by jandubois — CHANGES_REQUESTED** [review]
Requesting changes to prevent the PR from being merged; but I really think this PR should be closed because the current implementation is already correct (on macOS).

**Comment by jandubois** [comment]
For reference: [macOS Library Directory Details](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/MacOSXDirectories/MacOSXDirectories.html)

**Comment by jandubois** [comment]
> I really think this PR should be closed because the current implementation is already correct (on macOS).

We talked about this in person and agreed to reject the PR.

**Review by ericpromislow — COMMENTED** [review]
This is wrong. Split the config files on Linux, but point Linux AppHome to `~/.local/share/r-d`

The config files on macOS are fine.

**Pull request closed without merging**
