### PR TITLE
Fix moby pull output

### PR DESCRIPTION
**Pull request by ericpromislow**
Let's get the output window for `moby-pull-image` looking good again.

### CODE REVIEW

**Review by mook-as — CHANGES_REQUESTED** [review]
Please rebase; this appears to have pulled in changes meant for #1320.

**Comment by ericpromislow** [comment]
Done, thx for the heads-up

**Comment by mook-as** [comment]
Do you have sample output of what should be filtered out? I did a pull of `opensuse/leap`, and the output didn't have any lines that would be filtered out.

<details><summary>Output before PR</summary>

```
latest: Pulling from opensuse/leap

23d6a119e251: Pulling fs layer

23d6a119e251: Verifying Checksum
23d6a119e251: Download complete

23d6a119e251: Pull complete

Digest: sha256:c677acd52359c5c2012e9eeb1d33f3741a0eb5a39c4458126da7965f48d820b6

Status: Downloaded newer image for opensuse/leap:latest

docker.io/opensuse/leap:latest
```
</summary>

**Comment by ericpromislow** [comment]
When I grab sample output, I run it within a `script` session, so the CLI thinks it's writing to a TTY. I'm pretty sure if I redirect stdout I lose the formatting info.

**Comment by ericpromislow** [comment]
```
$ docker pull opensuse/leap 2>&1 | tee suse-out.txt
...
$ cat -v suse-out.txt | head
Using default tag: latest
latest: Pulling from opensuse/leap
23d6a119e251: Pulling fs layer
$ docker rmi opensuse/leap
$ script suse-out-script.txt
chirico:desktop(1262-install) $ docker pull opensuse/leap
..
chirico:desktop(1262-install) $ exit
$ cat -v suse-out-script.txt | head
Script started on Thu Jan 27 10:53:18 2022
chirico:desktop(1262-install) $ docker pull opensuse/leap^M
Using default tag: latest^M
latest: Pulling from opensuse/leap^M
^M
^[[1A^[[2K^M23d6a119e251: Pulling fs layer ^M^[[1B^[[1A^[[2K^M23d6a119e251: Downloading [>                                                  ]  437.5kB/43.18MB^M^[[1B^[[1A^[[2K^M23d6a119e251: Downloading [==>                                                ]   2.19MB/
...
```

The UI sees the second kind of run, not the first.

If I could pipe the output from `docker` through `cat` this wouldn't be necessary -- maybe that's a better solution.

Or is there a hidden option to force plain output?

**Comment by mook-as** [comment]
Hmm,
1. You're giving output that _isn't_ being copied from the app;
2. Your sample doesn't contain the lines you intend to filter out.

Would you be able to reproduce the problem in the app? My issue is that I can't see those lines, so I'm trying to figure out what I'm doing wrong…

Thanks!

**Comment by ericpromislow** [comment]
Problem was with nerdctl, not moby.

**Pull request closed without merging**
