### PR TITLE
Display and accept virtiofs on Linux

### PR DESCRIPTION
**Pull request by s0nea**
Screenshot_2023-07-18_12-40-54

Fixes: https://github.com/rancher-sandbox/rancher-desktop/issues/5110

### CODE REVIEW

**Review by rak-phillip — COMMENTED** [review]
Testing this PR in openSUSE Tumbleweed and I'm unable to access the virtiofs option

image

**Comment by jandubois** [comment]
PR needs to be rebased to resolve merge conflicts.

**Comment by s0nea** [comment]
> Testing this PR in openSUSE Tumbleweed and I'm unable to access the virtiofs option
> 
> image

Oh... that's interesting :thinking: I made the screenshot on openSUSE Leap.

**Comment by s0nea** [comment]
> PR needs to be rebased to resolve merge conflicts.

Done!

**Comment by s0nea** [comment]
> @s0nea LGTM It definitely works as advertised now. I suspect that I had some zombie nuxt processes that I didn't clean up after troubleshooting e2e tests yesterday.

Okay, great. Thank you for checking it again @rak-phillip!

**Pull request merged**
