### PR TITLE
Add extension icon as part of installed list

### PR DESCRIPTION
**Pull request by s0nea**
Before:
Screenshot_2023-08-02_15-04-44

After:
Screenshot_2023-08-04_15-17-27
Screenshot_2023-08-04_at_15 25 12

Fixes: https://github.com/rancher-sandbox/rancher-desktop/issues/5207

### CODE REVIEW

**Comment by ericpromislow** [comment]
This isn't working -- the image takes up almost the whole window/viewport

Screen Shot 2023-08-02 at 11 21 32 AM

**Review by ericpromislow — CHANGES_REQUESTED** [review]
See my screenshot for where this didn't work for me.

Adding

```

  img {
    height: 34px;
    width: 34px;
  }
```

to `pkg/rancher-desktop/components/NavIconExtension.vue` fixed it.

**Comment by s0nea** [comment]
> See my screenshot for where this didn't work for me.
> 
> Adding
> 
> ```
> 
>   img {
>     height: 34px;
>     width: 34px;
>   }
> ```
> 
> to `pkg/rancher-desktop/components/NavIconExtension.vue` fixed it.

Oh! Thank you for catching it. I'll update the PR.

**Review by ericpromislow — APPROVED** [review]
Looks good

**Pull request merged**
