### PR TITLE
Disable opening preferences window if Kubernetes is in Stopping/Stopped state

### LINKED ISSUE #2678: When RD is shutting down, opening the preferences dialog results in a window with no content
### Actual Behavior

The same behaviour shows whether the preferences dialog is opened via the gear icon in the top right corner, via "Preferences" in the dock, or via `ctrl+,`.

### Steps to Reproduce

1. Run Rancher Desktop via `npm run dev` and wait until it is finished starting.
2. Shut Rancher Desktop down via "Quit Rancher Desktop" in the dock.
3. Use any method to open the preferences dialog.

### Result

image

### Expected Behavior

While shutting down, each method of opening the preferences dialog should be grayed out and nonfunctional.

### Additional Information

_No response_

### Rancher Desktop Version

1.5.0

### Rancher Desktop K8s Version

1.24.3

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

Pop OS 20.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by rak-phillip**
This disables opening the Preferences window while Kubernetes is in a Stopping/Stopped state. This PR disables multiple modes of opening the preferences window, including

* Tray Menu
* Application Menu
* Application Shortcut (`Ctrl+,`/`Cmd+,`)
* Preferences Button

closes #2678

### CODE REVIEW

**Review by mook-as — DISMISSED** [review]
This makes it impossible to re-enable Kubernetes if it's disabled (because it would not be running).

**Comment by rak-phillip** [comment]
@mook-as I haven't experienced this.. can you explain why you think this is? We should have the `State.DISABLED` to handle your concern. In my testing, I didn't experience this behavior at all.

Screen Shot 2022-09-20 at 5 19 34 PM

Screen Shot 2022-09-20 at 5 19 37 PM



However I did notice that I needed to fix my `isDisabled` check in `Header.vue` after I refactored to make use of a preferences utility.

**Comment by mook-as** [comment]
Hmm, I had issues at 3902360 but the current tip seems to work better.

**Comment by rak-phillip** [comment]
> Hmm, I had issues at [3902360](https://github.com/rancher-sandbox/rancher-desktop/commit/3902360aa5b98434174b36a64e3cd229e3d73ae4) but the current tip seems to work better.

OK, that makes sense. That's the commit where I pulled out a lot of duplicate check for the same state into a utility but didn't take into account the disabled property for the button in the main window header.

Thanks for the update 🙂

**Comment by rak-phillip** [comment]
Closing this PR because we nee a more robust solution outside of Kubernetes/VM state in order to handle this properly.

Created issue #2967 to start considering how we might want to approach this change.

**Pull request closed without merging**
