### PR TITLE
Install tools in WSL

### LINKED ISSUE #325: KIM installed onto 3rd party WSL
As an existing user of WSL, it would be nice if I could easily install KIM into my current WSL install. 

This likely shouldn't be done without user interaction since it changes the PATH. My suggestion would be a dropdown to select which WSL to install into.

### PR DESCRIPTION
**Pull request by mook-as**
This adds the Linux tools in `…/resources/linux/bin/` (and added to `PATH` in the installer / removed in the uninstaller).  This also includes a fix to the uninstaller to actually remove the entries correctly.

I've opted to use a separate directory, as otherwise it is unclear why those files exist (since running them on Windows would just produce an error).

Fixes #325 — I actually tested that `kubectl` works (running `kuberlr`, which produced errors as I wasn't running Rancher Desktop).

### CODE REVIEW

**Review by ericpromislow — CHANGES_REQUESTED** [review]
So the changes look ok, but it takes a long time to run all four linux binaries in the ubuntu/wsl sub-system:
```
$ for x in * ; do echo $x ; time ./$x -h 2>&1 >/dev/null; done
helm
helm

real    0m8.689s
user    0m0.121s
sys     0m1.207s

kim

real    0m9.766s
user    0m0.229s
sys     0m1.422s

kubectl
real    0m4.054s
user    0m0.000s
sys     0m0.477s
kuberlr

real    0m5.095s
user    0m0.031s
sys     0m0.670s

On macos, all of them run in less than 50 msec wallclock time.

Running a native linux command through `wsl` is instant, so there seems to be something wrong here.

**Comment by mook-as** [comment]
I believe it's because the binaries are on the Windows side (NTFS, typically), which means they get mounted on the WSL VM via drvfs which can be slow (because, IIRC, that's essentially a networked filesystem).

We may need to copy the files to some Linux-native filesystem (say, the rancher-desktop distro) and share that to all distros.

**Comment by mook-as** [comment]
It's fairly easy to (from the rancher-desktop distribution) copy files to `/mnt/wsl/…` somewhere so it gets shared across all (v2) distros.  However, there doesn't seem to be a good way to add that to the path; the Windows `PATH` can only be used with Windows-style paths (i.e. not things in the VM).  So having `/mnt/…` in the (Windows-side) `PATH` doesn't work; it never gets transferred to WSL.  Same with `\\wsl$\…` style.

I think we may have to just ignore that, and run the Linux tools from the Windows partition (with the slowdown that entails); the user is still free to copy the files over themselves if that is too slow.  We _may_ want to revisit this after we get better WSL integration via #326, since that will provide infrastructure to do per-distro integration; in the mean time, I think we should merge this as-is even though it's a bit slower.

@ericpromislow thoughts?

**Review by ericpromislow — APPROVED** [review]

**Comment by mook-as** [comment]
Added #413 to investigate making the Linux binaries faster.

**Review by Yoseph11th — APPROVED** [review]
Good morning

**Pull request merged**
