### PR TITLE
Bump lima to revert the QEMU guest agent communication method

### LINKED ISSUE #6151: Guest agent fails to restart when the VM restarts
### Actual Behavior

When creating a deployment and service via Kubernetes with containerd and switching to dockerd, the guest agent fails to start, causing an error in port forwarding

### Steps to Reproduce

1. Run Rancher Desktop with containerd
2. Create a deployment and a service: 
```
kubectl create deployment nginx-test --image=nginx:stable
kubectl create service clusterip nginx-test --tcp=5000:80
```
3. Switch to dockerd

### Result

Fatal error occurs:

```
'time="2023-12-07T13:44:01-08:00" level=info msg="[hostagent] Forwarding \\"/var/run/docker.sock\\" (guest) to \\"/Users/iguimaraes/.rd/docker.sock\\" (host)"\n' +
    'time="2023-12-07T13:45:01-08:00" level=info msg="[hostagent] Waiting for the final requirement 1 of 1: \\"boot scripts must have finished\\""\n' +
    'time="2023-12-07T13:45:01-08:00" level=info msg="[hostagent] The final requirement 1 of 1 is satisfied"\n' +
    'time="2023-12-07T13:45:01-08:00" level=error msg="[guest agent does not seem to be running; port forwards will not work]"\n' +
    'time="2023-12-07T13:45:01-08:00" level=warning msg="DEGRADED. The VM seems running, but file sharing and port forwarding may not work. (hint: see \\"/Users/iguimaraes/Library/Application Support/rancher-desktop/lima/0/ha.stderr.log\\")"\n' +
    'time="2023-12-07T13:45:01-08:00" level=fatal msg="degraded, status={Running:true Degraded:true Exiting:false Errors:[guest agent does not seem to be running; port forwards will not work] SSHLocalPort:60612}"\n',
  code: 1,
  [Symbol(child-process.command)]: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura start --tty=false 0'
}
```

[lima-logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/13605837/lima-logs.zip)

[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/13605828/logs.zip)

### Expected Behavior

Application must restart with no errors

### Additional Information

_No response_

### Rancher Desktop Version

1.11.1-407-g4a132d0e

### Rancher Desktop K8s Version

1.27.7

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Ventura 13.5.2

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by jandubois**
Fixes #6151

Changes between `0.19.0.rd2` and `0.19.0.rd5` are: https://github.com/rancher-sandbox/lima/compare/ef739161deaa0dd78870e7e872d8bb371cd6376f...12546713676a07d150c790c9eac145d4eb1f9e39

### CODE REVIEW

**Comment by ericpromislow** [comment]
I get startup errors on linux in two different situations:

1. Situation 1: Running this as a dev build after running a previous dev build, with no factory-reset (this is less important than situation 2, covered after the paste):

```
Kubernetes Error
Rancher Desktop v1.11.1-512-g7ce5af986 - linux (x64)
Error Starting Kubernetes
Error: /home/ericp/workspace/rancher/desktop/resources/linux/lima/bin/limactl exited with code 1
stdout:

stderr:
time="2024-01-03T13:11:28-08:00" level=debug msg="interpreting argument \"0\" as an instance name"
time="2024-01-03T13:11:28-08:00" level=info msg="Using the existing instance \"0\""
time="2024-01-03T13:11:28-08:00" level=debug msg="Failed to look up socket_vmnet path \"/opt/socket_vmnet/bin/socket_vmnet\"" error="exec: \"/opt/socket_vmnet/bin/socket_vmnet\": stat /opt/socket_vmnet/bin/socket_vmnet: no such file or directory"
time="2024-01-03T13:11:28-08:00" level=debug msg="Failed to look up socket_vmnet path \"socket_vmnet\"" error="exec: \"socket_vmnet\": executable file not found in $PATH"
time="2024-01-03T13:11:28-08:00" level=debug msg="Failed to look up socket_vmnet path \"/usr/local/opt/socket_vmnet/bin/socket_vmnet\"" error="exec: \"/usr/local/opt/socket_vmnet/bin/socket_vmnet\": stat /usr/local/opt/socket_vmnet/bin/socket_vmnet: no such file or directory"
time="2024-01-03T13:11:28-08:00" level=debug msg="Failed to look up socket_vmnet path \"/opt/homebrew/opt/socket_vmnet/bin/socket_vmnet\"" error="exec: \"/opt/homebrew/opt/socket_vmnet/bin/socket_vmnet\": stat /opt/homebrew/opt/socket_vmnet/bin/socket_vmnet: no such file or directory"
time="2024-01-03T13:11:28-08:00" level=debug msg="Make sure \"user-v2\" network is stopped"
time="2024-01-03T13:11:28-08:00" level=debug msg="Make sure usernet network is stopped"
time="2024-01-03T13:11:28-08:00" level=debug msg="Make sure \"rancher-desktop-shared\" network is stopped"
time="2024-01-03T13:11:28-08:00" level=debug msg="Make sure \"host\" network is stopped"
time="2024-01-03T13:11:28-08:00" level=info msg="Starting the instance \"0\" with VM driver \"qemu\""
time="2024-01-03T13:11:28-08:00" level=debug msg="[hostagent] Creating iso file /home/ericp/.local/share/rancher-desktop/lima/0/cidata.iso"
time="2024-01-03T13:11:28-08:00" level=debug msg="[hostagent] Using /tmp/diskfs_iso3581110627 as workspace"
time="2024-01-03T13:11:28-08:00" level=debug msg="[hostagent] OpenSSH version 8.9.1 detected"
time="2024-01-03T13:11:28-08:00" level=debug msg="[hostagent] AES accelerator seems available, prioritizing aes128-gcm@openssh.com and aes256-gcm@openssh.com"
time="2024-01-03T13:11:28-08:00" level=info msg="[hostagent] hostagent socket created at /home/ericp/.local/share/rancher-desktop/lima/0/ha.sock"
time="2024-01-03T13:11:28-08:00" level=debug msg="[hostagent] Start udp DNS listening on: 127.0.0.1:46057"
time="2024-01-03T13:11:28-08:00" level=debug msg="[hostagent] Start tcp DNS listening on: 127.0.0.1:34797"
time="2024-01-03T13:11:28-08:00" level=debug msg="[hostagent] QEMU version 6.1.0 detected"
time="2024-01-03T13:11:28-08:00" level=debug msg="[hostagent] firmware candidates = [/home/ericp/.local/share/qemu/edk2-x86_64-code.fd /home/ericp/workspace/rancher/desktop/resources/linux/lima/share/qemu/edk2-x86_64-code.fd /usr/share/OVMF/OVMF_CODE.fd /usr/share/qemu/ovmf-x86_64-code.bin /usr/share/edk2-ovmf/x64/OVMF_CODE.fd]"
time="2024-01-03T13:11:28-08:00" level=info msg="[hostagent] Starting QEMU (hint: to watch the boot progress, see \"/home/ericp/.local/share/rancher-desktop/lima/0/serial*.log\")"
time="2024-01-03T13:11:28-08:00" level=debug msg="[hostagent] qCmd.Args: [/home/ericp/workspace/rancher/desktop/resources/linux/lima/bin/qemu-system-x86_64 -m 6144 -cpu host -machine q35,accel=kvm -smp 2,sockets=1,cores=2,threads=1 -drive if=pflash,format=raw,readonly=on,file=/home/ericp/workspace/rancher/desktop/resources/linux/lima/share/qemu/edk2-x86_64-code.fd -boot order=d,splash-time=0,menu=on -drive file=/home/ericp/.local/share/rancher-desktop/lima/0/basedisk,format=raw,media=cdrom,readonly=on -drive file=/home/ericp/.local/share/rancher-desktop/lima/0/diffdisk,if=virtio,discard=on -drive id=cdrom0,if=none,format=raw,readonly=on,file=/home/ericp/.local/share/rancher-desktop/lima/0/cidata.iso -device virtio-scsi-pci,id=scsi0 -device scsi-cd,bus=scsi0.0,drive=cdrom0 -netdev user,id=net0,net=192.168.5.0/24,dhcpstart=192.168.5.15,hostfwd=tcp:127.0.0.1:41177-:22 -device virtio-net-pci,netdev=net0,mac=52:55:55:7a:de:0d -device virtio-rng-pci -display none -device virtio-vga -device virtio-keyboard-pci -device virtio-mouse-pci -device qemu-xhci,id=usb-bus -parallel none -chardev socket,id=char-serial,path=/home/ericp/.local/share/rancher-desktop/lima/0/serial.sock,server=on,wait=off,logfile=/home/ericp/.local/share/rancher-desktop/lima/0/serial.log -serial chardev:char-serial -chardev socket,id=char-serial-virtio,path=/home/ericp/.local/share/rancher-desktop/lima/0/serialv.sock,server=on,wait=off,logfile=/home/ericp/.local/share/rancher-desktop/lima/0/serialv.log -device virtio-serial-pci,id=virtio-serial0,max_ports=1 -device virtconsole,chardev=char-serial-virtio,id=console0 -chardev socket,id=char-qmp,path=/home/ericp/.local/share/rancher-desktop/lima/0/qmp.sock,server=on,wait=off -qmp chardev:char-qmp -chardev socket,path=/home/ericp/.local/share/rancher-desktop/lima/0/ga.sock,server=on,wait=off,id=qga0 -device virtio-serial -device virtserialport,chardev=qga0,name=io.lima-vm.guest_agent.0 -name lima-0 -pidfile /home/ericp/.local/share/rancher-desktop/lima/0/qemu.pid]"
time="2024-01-03T13:11:28-08:00" level=debug msg="received an event" event="{2024-01-03 13:11:28.642598081 -0800 PST {false false false [] 41177}}"
time="2024-01-03T13:11:28-08:00" level=info msg="SSH Local Port: 41177"
time="2024-01-03T13:11:28-08:00" level=info msg="[hostagent] Waiting for the essential requirement 1 of 4: \"ssh\""
time="2024-01-03T13:11:28-08:00" level=debug msg="[hostagent] executing script \"ssh\""
time="2024-01-03T13:11:28-08:00" level=debug msg="[hostagent] executing ssh for script \"ssh\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/home/ericp/.local/share/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=ericp -o ControlMaster=auto -o ControlPath=\"/home/ericp/.local/share/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 41177 127.0.0.1 -- /bin/bash]"
time="2024-01-03T13:11:28-08:00" level=debug msg="[hostagent] stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 41177: Connection refused\\r\\n\", err=failed to execute script \"ssh\": stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 41177: Connection refused\\r\\n\": exit status 255"
time="2024-01-03T13:11:38-08:00" level=info msg="[hostagent] Waiting for the essential requirement 1 of 4: \"ssh\""
time="2024-01-03T13:11:38-08:00" level=debug msg="[hostagent] executing script \"ssh\""
time="2024-01-03T13:11:38-08:00" level=debug msg="[hostagent] executing ssh for script \"ssh\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/home/ericp/.local/share/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=ericp -o ControlMaster=auto -o ControlPath=\"/home/ericp/.local/share/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 41177 127.0.0.1 -- /bin/bash]"
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] stdout=\"\", stderr=\"\", err=<nil>"
time="2024-01-03T13:11:45-08:00" level=info msg="[hostagent] The essential requirement 1 of 4 is satisfied"
time="2024-01-03T13:11:45-08:00" level=info msg="[hostagent] Waiting for the essential requirement 2 of 4: \"user session is ready for ssh\""
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] executing script \"user session is ready for ssh\""
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] executing ssh for script \"user session is ready for ssh\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/home/ericp/.local/share/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=ericp -o ControlMaster=auto -o ControlPath=\"/home/ericp/.local/share/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 41177 127.0.0.1 -- /bin/bash]"
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] stdout=\"\", stderr=\"+ timeout 30s bash -c 'until sudo diff -q /run/lima-ssh-ready /mnt/lima-cidata/meta-data 2>/dev/null; do sleep 3; done'\\n\", err=<nil>"
time="2024-01-03T13:11:45-08:00" level=info msg="[hostagent] The essential requirement 2 of 4 is satisfied"
time="2024-01-03T13:11:45-08:00" level=info msg="[hostagent] Waiting for the essential requirement 3 of 4: \"sshfs binary to be installed\""
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] executing script \"sshfs binary to be installed\""
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] executing ssh for script \"sshfs binary to be installed\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/home/ericp/.local/share/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=ericp -o ControlMaster=auto -o ControlPath=\"/home/ericp/.local/share/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 41177 127.0.0.1 -- /bin/bash]"
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] stdout=\"/usr/bin/sshfs\\n\", stderr=\"+ timeout 30s bash -c 'until command -v sshfs; do sleep 3; done'\\n\", err=<nil>"
time="2024-01-03T13:11:45-08:00" level=info msg="[hostagent] The essential requirement 3 of 4 is satisfied"
time="2024-01-03T13:11:45-08:00" level=info msg="[hostagent] Waiting for the essential requirement 4 of 4: \"/etc/fuse.conf (/etc/fuse3.conf) to contain \\\"user_allow_other\\\"\""
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] executing script \"/etc/fuse.conf (/etc/fuse3.conf) to contain \\\"user_allow_other\\\"\""
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] executing ssh for script \"/etc/fuse.conf (/etc/fuse3.conf) to contain \\\"user_allow_other\\\"\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/home/ericp/.local/share/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=ericp -o ControlMaster=auto -o ControlPath=\"/home/ericp/.local/share/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 41177 127.0.0.1 -- /bin/bash]"
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] stdout=\"\", stderr=\"+ timeout 30s bash -c 'until grep -q ^user_allow_other /etc/fuse*.conf; do sleep 3; done'\\n\", err=<nil>"
time="2024-01-03T13:11:45-08:00" level=info msg="[hostagent] The essential requirement 4 of 4 is satisfied"
time="2024-01-03T13:11:45-08:00" level=info msg="[hostagent] Mounting \"/home/ericp\" on \"/home/ericp\""
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] executing ssh for preparing sshfs: /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/home/ericp/.local/share/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=ericp -o ControlMaster=auto -o ControlPath=\"/home/ericp/.local/share/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 41177 127.0.0.1 -- mkdir -p \"/home/ericp\"]"
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] Chosen driver \"builtin\""
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] executing ssh for remote sshfs: /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/home/ericp/.local/share/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=ericp -o ControlMaster=auto -o ControlPath=\"/home/ericp/.local/share/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 41177 127.0.0.1 -- sshfs \":/home/ericp\" \"/home/ericp\" -o slave -o allow_other]"
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] starting sftp server for /home/ericp"
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] waiting for remote ready"
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] generated script \"wait-for-remote-ready\" with map map[Dir:/home/ericp MaxTrial:30]: \"#!/bin/sh\\nset -eu\\ndir=\\\"/home/ericp\\\"\\nmax_trial=\\\"30\\\"\\nLANG=C\\nLC_ALL=C\\nexport LANG LC_ALL\\ni=0\\nwhile : ; do\\n # FIXME: not really robust\\n # spaces in file names are encoded as '\\\\040' in the mount table\\n if mount | sed 's/\\\\\\\\040/ /g' | grep \\\"on ${dir}\\\" | egrep -qw \\\"fuse.sshfs|osxfuse\\\"; then\\n echo '{\\\"return\\\":{}}'\\n exit 0\\n fi\\n sleep 1\\n if [ $i -ge ${max_trial} ]; then\\n echo >&2 \\\"sshfs does not seem to be mounted on ${dir}\\\"\\n exit 1\\n fi\\n i=$((i + 1))\\ndone\\n\""
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] executing ssh for script \"wait-for-remote-ready\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/home/ericp/.local/share/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=ericp -o ControlMaster=auto -o ControlPath=\"/home/ericp/.local/share/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 41177 127.0.0.1 -- /bin/sh]"
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] executed script \"wait-for-remote-ready\", stdout=\"{\\\"return\\\":{}}\\n\", stderr=\"\", err=<nil>"
time="2024-01-03T13:11:45-08:00" level=info msg="[hostagent] Mounting \"/tmp/rancher-desktop\" on \"/tmp/rancher-desktop\""
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] executing ssh for preparing sshfs: /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/home/ericp/.local/share/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=ericp -o ControlMaster=auto -o ControlPath=\"/home/ericp/.local/share/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 41177 127.0.0.1 -- mkdir -p \"/tmp/rancher-desktop\"]"
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] Chosen driver \"builtin\""
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] executing ssh for remote sshfs: /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/home/ericp/.local/share/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=ericp -o ControlMaster=auto -o ControlPath=\"/home/ericp/.local/share/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 41177 127.0.0.1 -- sshfs \":/tmp/rancher-desktop\" \"/tmp/rancher-desktop\" -o slave -o allow_other]"
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] starting sftp server for /tmp/rancher-desktop"
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] waiting for remote ready"
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] generated script \"wait-for-remote-ready\" with map map[Dir:/tmp/rancher-desktop MaxTrial:30]: \"#!/bin/sh\\nset -eu\\ndir=\\\"/tmp/rancher-desktop\\\"\\nmax_trial=\\\"30\\\"\\nLANG=C\\nLC_ALL=C\\nexport LANG LC_ALL\\ni=0\\nwhile : ; do\\n # FIXME: not really robust\\n # spaces in file names are encoded as '\\\\040' in the mount table\\n if mount | sed 's/\\\\\\\\040/ /g' | grep \\\"on ${dir}\\\" | egrep -qw \\\"fuse.sshfs|osxfuse\\\"; then\\n echo '{\\\"return\\\":{}}'\\n exit 0\\n fi\\n sleep 1\\n if [ $i -ge ${max_trial} ]; then\\n echo >&2 \\\"sshfs does not seem to be mounted on ${dir}\\\"\\n exit 1\\n fi\\n i=$((i + 1))\\ndone\\n\""
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] executing ssh for script \"wait-for-remote-ready\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/home/ericp/.local/share/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=ericp -o ControlMaster=auto -o ControlPath=\"/home/ericp/.local/share/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 41177 127.0.0.1 -- /bin/sh]"
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] executed script \"wait-for-remote-ready\", stdout=\"{\\\"return\\\":{}}\\n\", stderr=\"\", err=<nil>"
time="2024-01-03T13:11:45-08:00" level=info msg="[hostagent] Waiting for the guest agent to be running"
time="2024-01-03T13:11:45-08:00" level=debug msg="[hostagent] Forwarding unix sockets"
time="2024-01-03T13:11:45-08:00" level=info msg="[hostagent] Forwarding \"/var/run/docker.sock\" (guest) to \"/home/ericp/.rd/docker.sock\" (host)"
time="2024-01-03T13:11:45-08:00" level=info msg="[hostagent] Forwarding \"/run/lima-guestagent.sock\" (guest) to \"/home/ericp/.local/share/rancher-desktop/lima/0/ga.sock\" (host)"
time="2024-01-03T13:11:45-08:00" level=warning msg="[hostagent] connection to the guest agent was closed unexpectedlyGet \"http://lima-guestagent/v1/info\": read unix @->/home/ericp/.local/share/rancher-desktop/lima/0/ga.sock: read: connection reset by peer"
time="2024-01-03T13:11:55-08:00" level=info msg="[hostagent] Forwarding \"/run/lima-guestagent.sock\" (guest) to \"/home/ericp/.local/share/rancher-desktop/lima/0/ga.sock\" (host)"
time="2024-01-03T13:11:55-08:00" level=warning msg="[hostagent] connection to the guest agent was closed unexpectedlydial unix /home/ericp/.local/share/rancher-desktop/lima/0/ga.sock: connect: no such file or directory"

[repeated...]

time="2024-01-03T13:12:45-08:00" level=info msg="[hostagent] Waiting for the final requirement 1 of 1: \"boot scripts must have finished\""
time="2024-01-03T13:12:45-08:00" level=debug msg="[hostagent] executing script \"boot scripts must have finished\""
time="2024-01-03T13:12:45-08:00" level=debug msg="[hostagent] executing ssh for script \"boot scripts must have finished\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/home/ericp/.local/share/rancher-desktop/lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=ericp -o ControlMaster=auto -o ControlPath=\"/home/ericp/.local/share/rancher-desktop/lima/0/ssh.sock\" -o ControlPersist=yes -p 41177 127.0.0.1 -- /bin/bash]"
time="2024-01-03T13:12:45-08:00" level=debug msg="[hostagent] stdout=\"\", stderr=\"+ timeout 30s bash -c 'until sudo diff -q /run/lima-boot-done /mnt/lima-cidata/meta-data 2>/dev/null; do sleep 3; done'\\n\", err=<nil>"
time="2024-01-03T13:12:45-08:00" level=info msg="[hostagent] The final requirement 1 of 1 is satisfied"
time="2024-01-03T13:12:45-08:00" level=debug msg="received an event" event="{2024-01-03 13:12:45.598022041 -0800 PST {true true false [guest agent does not seem to be running; port forwards will not work] 41177}}"
time="2024-01-03T13:12:45-08:00" level=error msg="[guest agent does not seem to be running; port forwards will not work]"
time="2024-01-03T13:12:45-08:00" level=warning msg="DEGRADED. The VM seems running, but file sharing and port forwarding may not work. (hint: see \"/home/ericp/.local/share/rancher-desktop/lima/0/ha.stderr.log\")"
time="2024-01-03T13:12:45-08:00" level=fatal msg="degraded, status={Running:true Degraded:true Exiting:false Errors:[guest agent does not seem to be running; port forwards will not work] SSHLocalPort:41177}"

Last command run:
/home/ericp/workspace/rancher/desktop/resources/linux/lima/bin/limactl --debug start --tty=false 0

```

Situation 2: Run factory-reset, then run 1.11, docker-run a container, and shut down. Then run a build version with this change.
Error at startup:

```
Kubernetes Error
Rancher Desktop 1.11.1-512-g7ce5af986 - linux (x64)
Error Starting Kubernetes
Error: /home/ericp/workspace/rancher/desktop/dist/linux-unpacked/resources/resources/linux/lima/bin/limactl exited with code 1
Last command run:
/home/ericp/workspace/rancher/desktop/dist/linux-unpacked/resources/resources/linux/lima/bin/limactl start --tty=false 0

Context:
Starting virtual machine

Some recent [logfile](app://./index.html#) lines:
    'time="2024-01-03T13:27:50-08:00" level=warning msg="[hostagent] connection to the guest agent was closed unexpectedlydial unix /home/ericp/.local/share/rancher-desktop/lima/0/ga.sock: connect: no such file or directory"\n' +
    'time="2024-01-03T13:28:00-08:00" level=info msg="[hostagent] Waiting for the final requirement 1 of 1: \\"boot scripts must have finished\\""\n' +
    'time="2024-01-03T13:28:00-08:00" level=info msg="[hostagent] The final requirement 1 of 1 is satisfied"\n' +
    'time="2024-01-03T13:28:00-08:00" level=error msg="[guest agent does not seem to be running; port forwards will not work]"\n' +
    'time="2024-01-03T13:28:00-08:00" level=warning msg="DEGRADED. The VM seems running, but file sharing and port forwarding may not work. (hint: see \\"/home/ericp/.local/share/rancher-desktop/lima/0/ha.stderr.log\\")"\n' +
    'time="2024-01-03T13:28:00-08:00" level=fatal msg="degraded, status={Running:true Degraded:true Exiting:false Errors:[guest agent does not seem to be running; port forwards will not work] SSHLocalPort:38311}"\n',
  code: 1,
  [Symbol(child-process.command)]: '/home/ericp/workspace/rancher/desktop/dist/linux-unpacked/resources/resources/linux/lima/bin/limactl start --tty=false 0'
}
```

**Review by ericpromislow — CHANGES_REQUESTED** [review]
This doesn't seem to run on linux (ubuntu)

**Review by ericpromislow — CHANGES_REQUESTED** [review]
Same problem with a dev-build on macOS after a factory-reset. This just isn't working.

**Comment by jandubois** [comment]
Confirmed; the updated `limactl` only works with `systemd` images, but not Alpine. Please wait for fix...

**Review by ericpromislow — APPROVED** [review]
This is now working on macOS and linux

**Pull request merged**
