### PR TITLE
Handle code signing on Windows better

### PR DESCRIPTION
**Pull request by mook-as**
This adds a script that we can use to do code signing on Windows, starting from a zip archive from GitHub.  This means the release process will be:

1. Make a tag.  This lets GitHub generate a zip file (ignore the unsigned Setup exe)
2. Download the zip archive, and extract it once (to get a _different_ zip archive, because [GitHub](https://github.com/actions/upload-artifact/issues/39)).
3. Run `npm run sign -- path\to\your.zip`
4. Upload `dist/Rancher Desktop 1.2.3 Setup.exe` — That's a signed installer, including a signed uninstaller, and also the main executable itself is signed.

Unfortunately electron-builder doesn't really do the right thing here, and I had to do some hacky hooking to get the main executable to be signed correctly.

Note that I've opted _not_ to sign `kubectl.exe` etc, since that's technically not ours (if anything, they should be signed by the appropriate upstreams).

I intend to start working on macOS support once this is merged (as it will likely be based on this code).

### CODE REVIEW

**Review by ericpromislow — CHANGES_REQUESTED** [review]
Had some problems trying to sign the build, and changed the sign line in `package.json` to this:
```
"sign": "ts-node --compiler-options \"{\\\"module\\\": \\\"commonjs\\\"}\" ./scripts/sign.ts",
```

**Review by mattfarina — COMMENTED** [review]
I'm getting an error when I go to sign... have not looked into the details yet...

```powershell
PS C:\Users\Matt\Code\rd> npm run sign -- '.\dist\Rancher Desktop-0.3.0-16-g9cb094b-win.zip'

> rancher-desktop@0.3.0 sign C:\Users\Matt\Code\rd
> ts-node --compiler-options '{"module": "commonjs"}' ./scripts/sign.ts ".\dist\Rancher Desktop-0.3.0-16-g9cb094b-win.zip"

undefined:1
'{module:
^

SyntaxError: Unexpected token ' in JSON at position 0
```

**Comment by mook-as** [comment]
NodeJS 14 compatibility fixed (with a wrapper script), as well as all the mentioned typos (I think; there were rather quite a few of them).

**Comment by mattfarina** [comment]
I'm still not able to run the script. You can see my errors [here](https://gist.github.com/mattfarina/03284261570aca04b1af0061a912495e).

**Comment by mook-as** [comment]
Relevant snippet from that paste:
```typescript
  ⨯ Cannot use 'in' operator to search for 'file' in undefined  stackTrace=
                                                                  TypeError: Cannot use 'in' operator to search for 'file' in undefined
                                                                      at Object.doSign (C:\Users\Matt\Code\rd\node_modules\app-builder-lib\src\codeSign\windowsCodeSign.ts:145:49)
                                                                      at windowsHook (C:\Users\Matt\Code\rd\scripts\sign.ts:103:15)
```

I can reproduce the issue if the `CSC_LINK`  / `CSC_KEY_PASSWORD` environment variables are not set as expected.  I'll modify the script to catch this to give you a better error message.

**Comment by mattfarina** [comment]
Now I'm getting a different error. https://gist.github.com/mattfarina/6a9bc75345ca2bd2918c98faea82a112

Sharing this now as I'll be out and have not tracked down the issue (on my end or in the script)

**Comment by ericpromislow** [comment]
An error message is needed when the user runs `npm run sign` with no arguments.

**Comment by mook-as** [comment]
In actually trying to sign things, we find that our cert will be on a USB stick emulating a smart card: we will _not_ have a `.pfx` file available (because the private key never leaves the USB stick).  We'll need to adjust things a bit.

**Comment by mook-as** [comment]
Obsoleted by #405

**Pull request closed without merging**
