### PR TITLE
rdctl factory-reset now kills the app and never waits.

### LINKED ISSUE #3493: `rdctl factory-reset`: drop the `--wait=false`option, stop waiting for the app and always kill it -- no need to wait
### Actual Behavior

I accidentally tried to repro #3467 on Windows 10 instead of macOS, and the reset failed with an "Access is denied" error.

### Steps to Reproduce

rdctl factory-reset --wait=false

### Result

```console
C:\Users\Jan>rdctl factory-reset --wait=false
time="2022-11-29T15:26:21-08:00" level=error msg="Problem trying to delete C:\\Users\\Jan\\AppData\\Local/rancher-desktop/cache/Rancher Desktop: remove C:\\Users\\Jan\\AppData\\Local/rancher-desktop/cache/Rancher Desktop\\Cache\\Cache_Data\\data_0: Access is denied.\n"
time="2022-11-29T15:26:21-08:00" level=error msg="Problem trying to delete C:\\Users\\Jan\\AppData\\Roaming/rancher-desktop: remove C:\\Users\\Jan\\AppData\\Roaming/rancher-desktop\\lockfile: The process cannot access the file because it is being used by another process.\n"

C:\Users\Jan>wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu-20.04 (Default)
openSUSE-Leap-15.2
```

The application is still running, but obviously no longer functional because the distro had been deleted.

### Expected Behavior

The would terminated normally without error and all configuration data is removed.

### Additional Information

_No response_

### Rancher Desktop Version

https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3578250286

### Rancher Desktop K8s Version

1.25.4

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

_No response_

### Windows User Only

Running in a VM

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #3493

Signed-off-by: Eric Promislow <epromislow@suse.com>

### CODE REVIEW

**Review by mook-as — CHANGES_REQUESTED** [review]
This does not work on Windows:
>     rdctl factory-reset
>     time="2022-11-30T11:50:00-08:00" level=error msg="Problem trying to delete C:\\Users\\Joe\\AppData\\Local/rancher-desktop/cache/Rancher Desktop: remove C:\\Users\\Joe\\AppData\\Local/rancher-desktop/cache/Rancher Desktop\\Local Storage\\leveldb\\000003.log: The process cannot access the file because it is being used by another process.\n"
>     time="2022-11-30T11:50:00-08:00" level=error msg="Problem trying to delete C:\\Users\\Joe\\AppData\\Local/rancher-desktop/logs: remove C:\\Users\\Joe\\AppData\\Local/rancher-desktop/logs: The process cannot access the file because it is being used by another process.\n"
>     time="2022-11-30T11:50:00-08:00" level=error msg="Problem trying to delete C:\\Users\\Joe\\AppData\\Roaming/rancher-desktop: remove C:\\Users\\Joe\\AppData\\Roaming/rancher-desktop\\lockfile: The process cannot access the file because it is being used by another process.\n"

Note that after all this, Rancher Desktop is _still running_. However, the log files have been deleted, so I can't see what happened.

I imagine this is because we went from `--wait=true` by default to `--wait=false`, all the time, without changing anything about how anything else is implemented.

**Comment by jandubois** [comment]
> I imagine this is because we went from `--wait=true` by default to `--wait=false`, all the time, without changing anything about how anything else is implemented.

The code is supposed to run `factoryreset.KillRancherDesktop()` before deleting the files. Maybe it still needs to wait for it? On Linux/macOS it is `kill -9`ing both qemu and rancher-desktop processes.

**Comment by ericpromislow** [comment]
I added a commit -- now it always waits. I also noticed that the Windows `taskkill` command is failing to find the `"Rancher Desktop"` process, even with a packaged build. Can we leave this for later?

**Comment by ericpromislow** [comment]
Finally figured out how to make process killing work on Windows. So now we never wait and always kill before starting to delete files.

Still only works for packaged builds.

**Review by mook-as — APPROVED** [review]

**Pull request merged**
