### PR TITLE
Rename the 'k3s' instance to 'rancher-desktop'

### PR DESCRIPTION
**Pull request by ericpromislow**
Signed-off-by: Eric Promislow <epromislow@suse.com>

### CODE REVIEW

**Review by mook-as — APPROVED** [review]
I'd probably call it `DISTRO_NAME` or `DISTRIBUTION_NAME` instead, but that's not really an issue.

**Comment by ericpromislow** [comment]
It was initially called `DISTRO_NAME` but I realized the distro is always going to be `k3s`, but we're creating an instance of that distro, and `DISTRO_INSTANCE_NAME` felt too long. But that would be my choice over `INSTANCE_NAME`

**Comment by jandubois** [comment]
> It was initially called `DISTRO_NAME` but I realized the distro is always going to be `k3s`,

I don't think it matters much, but `rancher-desktop` really *is* the distribution name. There is no such things as instances of a distribution; you can just have multiple distributions that were initialized from the same tarball. But it really only becomes a distribution when it has been instantiated by WSL (i.e. it has a local ext4 volume to store the data).

Maybe think of a distribution of something like a container, and the tarball being the image. Calling the container name an "instance name" of the container image is just confusing to me.

**Comment by ericpromislow** [comment]
I'm confused now. I thought we're running the `k3s` kubernetes distribution, and the name `rancher-desktop` is going to be exposed to the user when they run `wslconfig ...` or `wsl -d DISTRO_NAME`

**Comment by ericpromislow** [comment]
Going to merge anyway. The name can always be changed -- it's just a javascript constant that doesn't get exposed to the user.

**Pull request merged**
