### PR TITLE
Bump alpine-lima iso from v0.2.1 → v0.2.2

### PR DESCRIPTION
**Pull request by jandubois**
continues #1014, which got erroneously close and somehow cannot be re-opened

### CODE REVIEW

**Review by mook-as — APPROVED** [review]
Carrying approval over from #1014.

**Comment by jandubois** [comment]
I've convinced myself now that persisting all of `/etc` in Lima has been a mistake, and unfortunately needs to be fixed there:

When the VM starts with an updated ISO, the new `/etc` is ignored, and any changed made by lima boot scripts are done against the old persisted version. So there is no way to switch to the newer version and having the changes applied to that version instead.

I'll create a PR for Lima, making the set of directories moved to the persistent volume configurable. Then we can drop `/etc` and add just individual subdirectories, like `/etc/docker`, `/etc/rancher`, and `/etc/ssh`. This should even work for upgrades; the rest of the persisted `/etc` will just be ignored when the list is getting more restrictive.

On second thought, we could force a reboot in the provisioning script after updating the persistent version of `/etc`, and on the reboot all changes will then be applied to the up-to-date version. Feels somewhat dirty, but easier to implement, so I'll try that first...

**Comment by jandubois** [comment]
> Feels somewhat dirty, but easier to implement, so I'll try that first...

Seems to work in testing, so maybe good enough for the 0.7.0 release. There is only a single reboot once the ISO changes, not every time the VM restarts.

**Review by ericpromislow — APPROVED** [review]
works fine now

**Pull request merged**
