### PR TITLE
[Fix] Electron upgrade

### PR DESCRIPTION
**Pull request by evertonlperes**
### Changes
1. Upgraded `electron` from `12.0.8` to `13.6.1`
2. Upgraded `spectron` from `14.0.0` to `15.0.0`

### Fixes
* Attempt to fix `ipcRenderer.SendSync` intermittency during E2E tests -> [#855 ](https://github.com/rancher-sandbox/rancher-desktop/pull/855)

Note: There's a major fixes/improvements started on Electron `13.0.0` and comparing the our current version vs `13.6.1`, it has many fixes/improvements that could have fixed the issue on `ipcRenderer.SendSync`.
Ref: [v13.6.1](https://www.electronjs.org/releases/stable?page=3#13.6.1)

### Results
During the performance test, upgrading Electron seemed to fixed the intermittent issue during the E2E tests (see [#885](https://github.com/rancher-sandbox/rancher-desktop/pull/855) for details).
* Using Electron `v13.6.1` - 20 executions (100% PASS - 0% FAIL)
* Using Electron `v12.0.8` - 1 executions, ( 50% PASS - 50% FAIL)

**Logs**
[electron_12_0_18_jest_e2e_performance.log](https://github.com/rancher-sandbox/rancher-desktop/files/7500790/electron_12_0_18_jest_e2e_performance.log)
[electron_13_6_1_jest_e2e_performance_01.log](https://github.com/rancher-sandbox/rancher-desktop/files/7500791/electron_13_6_1_jest_e2e_performance_01.log)
[electron_13_6_1_jest_e2e_performance_02.log](https://github.com/rancher-sandbox/rancher-desktop/files/7500792/electron_13_6_1_jest_e2e_performance_02.log)

### How to test
1. Remove `node_modules` folder (`rm -rf node_modules`)
2. Run `npm install` and `npm run build` --> it will build the electron binary using version 13
3. Run `npm run test:e2e`

### CODE REVIEW

**Comment by evertonlperes** [comment]
@mook-as 
Found a issue during the version updater and I'd like to double check if it could be related to the new Electron Version 13:
```bash
2021-11-09T22:55:02.097Z: Update is cached; forcing re-check to install.
2021-11-09T22:55:02.097Z: Checking for update
2021-11-09T22:55:03.643Z: Found version v0.6.1 (url: https://github.com/rancher-sandbox/rancher-desktop/releases/download/v0.6.1/Rancher.Desktop-0.6.1-mac.zip)
2021-11-09T22:55:03.643Z: Downloading update from https://github.com/rancher-sandbox/rancher-desktop/releases/download/v0.6.1/Rancher.Desktop-0.6.1-mac.zip
2021-11-09T22:55:04.209Z: Update has already been downloaded to /Users/evertonperes/Library/Application Support/Caches/rancher-desktop-updater/pending/Rancher.Desktop-0.6.1-mac.zip).
2021-11-09T22:55:04.214Z: Error: Could not get code signature for running application
2021-11-09T22:55:04.214Z: Error: Error: Could not get code signature for running application
    at Server.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:105:44)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:315:20)
    at emitListeningNT (net.js:1352:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
2021-11-09T22:55:04.214Z: Updater got error Error: Could not get code signature for running application
    at Server.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:105:44)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:315:20)
    at emitListeningNT (net.js:1352:10)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
2021-11-09T22:55:04.215Z: Update download complete; restarting app
2021-11-09T22:55:04.215Z: Install complete, result: false
```
Is that the error that you and @ericpromislow have found?

**Comment by mook-as** [comment]
No, `Could not get code signature` means you're running an unsigned, local build.  Try to make a self-signed certificate for local testing - see [Apple's guide](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html#//apple_ref/doc/uid/TP40005929-CH4-SW30) (look for the section "To obtain a self-signed certificate using Certificate Assistant" under "Obtaining Your Signing Identities").

Note though, I believe you need to use the same certificate to do the actual upgrade — so you'll need to set up your own test builds.

**Comment by evertonlperes** [comment]
> No, `Could not get code signature` means you're running an unsigned, local build. Try to make a self-signed certificate for local testing - see [Apple's guide](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html#//apple_ref/doc/uid/TP40005929-CH4-SW30) (look for the section "To obtain a self-signed certificate using Certificate Assistant" under "Obtaining Your Signing Identities").
> 
> Note though, I believe you need to use the same certificate to do the actual upgrade — so you'll need to set up your own test builds.

Got it working using `codesign` and the existing local certificates: `codesign --deep --force --verbose --sign - /dist/[distro]/Rancher Desktop.[extension]`
Screen Shot 2021-11-10 at 11 51 04 AM

**Comment by evertonlperes** [comment]
Closing it for now.
We can upgrade Electron on the near future.
It can be a solution for fix the `sendSync` errors, but the recommended fix is to replace `sendSync` methods to `invoke`. See: https://github.com/rancher-sandbox/rancher-desktop/pull/949

**Pull request closed without merging**
