### PR TITLE
Stop pinning to a non-non-existent version of nginx and curl it through the nodeport.

### PR DESCRIPTION
**Pull request by ericpromislow**
No associated issue, but fixes a frequently failing e2e test.

Signed-off-by: Eric Promislow <epromislow@suse.com>

### CODE REVIEW

**Review by jandubois — CHANGES_REQUESTED** [review]
I don't see any evidence that the chart or image no longer exists. I just installed the chart on a factory-reset 1.7.0 install, and it seems to be working.

**Comment by jandubois** [comment]
```console
$ nerdctl -n k8s.io images | grep nginx
bitnami/nginx                       1.23.1-debian-11-r29    7b395923d600    2 minutes ago    linux/amd64    104.9 MiB    37.0 MiB
bitnami/nginx                       <none>                  7b395923d600    2 minutes ago    linux/amd64    104.9 MiB    37.0 MiB
```

**Comment by mook-as** [comment]
I thought the whole point of using a pinned version is so we keep using something with curl in it…
```
$ curl https://charts.bitnami.com/bitnami/index.yaml | yq '.entries.nginx.[] | select(.version == "13.2.9") | .urls.[]'
https://charts.bitnami.com/bitnami/nginx-13.2.9.tgz
```

**Comment by ericpromislow** [comment]
Yes, exactly.

For some reason this version of the helm chart wasn't available on Jan 20/2023, but it's back now (?). And Jan wants to keep doing `kubernetes exec ... ; curl locahost:PORT` because it is a reasonable use case.

**Review by mook-as — CHANGES_REQUESTED** [review]
Please update your commit message to better explain _why_ this fixes things. For one thing, that version of the `bitnami/nginx` helm chart still exists, and still points to an image that contains `curl`.

**Comment by ericpromislow** [comment]
We aren't going to do this, as long as this version of the helm chart exists.

**Pull request closed without merging**
