### PR TITLE
Display app version and platform in kubernetes error dialog

### LINKED ISSUE #1933: Provide platform and version on the error message dialog
### Problem Description

People are posting screen shots of the main error message dialog, so we might as well put the platform and version there for when they don't provide it.

### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### PR DESCRIPTION
**Pull request by rak-phillip**
This displays the app version and platform as a description below the header in the kubernetes error dialog.

closes #1933

### CODE REVIEW

**Comment by rak-phillip** [comment]
### Example

image

**Comment by mook-as** [comment]
We may also want the CPU (x86_64 / arm64) in there, too, for mac people.

**Comment by rak-phillip** [comment]
@mook-as great point, fixed 🙂

**Review by ericpromislow — APPROVED** [review]
LGTM

**Pull request merged**
