### PR TITLE
Quit Rancher Desktop when a snapshot fails to restore

### LINKED ISSUE #5809: After snapshot operations fails, Rancher Desktop stays in a broken state
### Actual Behavior

If an error occurs while creating a snapshot, a pop up is displayed from the main window with a clickable button to `Show logs`. However, it fails to open the logs directory. After more investigation, it's possible to verify that the directory no longer exists and that a factory reset is performed but the VM is not restarted.

### Steps to Reproduce

1. Try to create a snapshot with `.DS_Store` in the snapshots directory
2. Try to open the logs directory by clicking `Show logs` from the error pop up that is displayed when the operation fails

### Result

Screenshot 2023-10-20 at 10 46 16 AM

Factory reset removes the application resources and configuration, however the VM does not restart and the UI remains interactive.

```
ls $HOME/Library/Logs/rancher-desktop
ls: /Users/iguimaraes/Library/Logs/rancher-desktop: No such file or directory
```

```
ls $HOME/Library/Caches/rancher-desktop
ls: /Users/iguimaraes/Library/Caches/rancher-desktop: No such file or directory
```

```
ls "$HOME/Library/Application Support/rancher-desktop"

```
`Application Support/rancher-desktop` is empty

### Expected Behavior

When a snapshot operation fails, a factory reset must be performed and the VM must be restarted

### Additional Information

_No response_

### Rancher Desktop Version

1.10.0-455-g9e9a293a

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Ventura 13.5.2

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

_No response_

### PR DESCRIPTION
**Pull request by rak-phillip**
This PR quits Rancher Desktop when a snapshot fails to restore. It also disables the Restore button while Rancher Desktop is starting, this is compromise that will eliminate a failure mode that happens when attempting to restore from a snapshot while Rancher Desktop is starting. 

## Notes

Rancher Desktop should only quit when the two following conditions are fulfilled: 

1. A Snapshot is being restored 
2. The restore process fails

Other modes of failure during the snapshot creation process should behave as they did before

closes #5809

### CODE REVIEW

**Review by ericpromislow — CHANGES_REQUESTED** [review]
Code looks good, and it did as advertised, but the user needs to be clearly advised that Rancher Desktop will shut down immediately after they press the `OK` button in the dialog with the snapshot-restore error message.

**Comment by rak-phillip** [comment]
> Code looks good, and it did as advertised, but the user needs to be clearly advised that Rancher Desktop will shut down immediately after they press the `OK` button in the dialog with the snapshot-restore error message.

@ericpromislow this is what the dialog looks like when it enters an error state. 

image

I'm not the happiest with the implementation and I will follow up with issues to improve the implementation.

**Comment by jandubois** [comment]
I have not reviewed/tested the PR, but the dialog looks fine to me.

Only quibble would be that the Factory Reset has already been performed at that time; not sure if that should be reworded). I just mention it because somebody could try to kill the app instead of pressing the Quit button, to avoid the Factory Reset, which obviously would not actually work.

**Comment by rak-phillip** [comment]
> I have not reviewed/tested the PR, but the dialog looks fine to me.
> 
> Only quibble would be that the Factory Reset has already been performed at that time; not sure if that should be reworded). I just mention it because somebody could try to kill the app instead of pressing the Quit button, to avoid the Factory Reset, which obviously would not actually work.

Right, that's a good point. I'll try to reword this so that it better represents reality.

**Comment by rak-phillip** [comment]
@jandubois I updated the message to make it more clear that the Factory Reset already took place, what do you think?

image

**Comment by jandubois** [comment]
> I updated the message to make it more clear that the Factory Reset already took place, what do you think?

Yes, sounds good.

I wonder if we should include some verbiage about trying to fix the root cause of the failure to restore the snapshot before trying to restore again. E.g. when the problem was a lack of space, then simply trying again is not going to work; you will need to free up some space before trying again.

**Comment by rak-phillip** [comment]
> I wonder if we should include some verbiage about trying to fix the root cause of the failure to restore the snapshot before trying to restore again. E.g. when the problem was a lack of space, then simply trying again is not going to work; you will need to free up some space before trying again.

I agree, including verbiage about addressing the problem and potential solutions is a great idea. However, we currently lack detailed error information on the frontend at this point. We'll have to follow-up later to review our error messages.

**Comment by jandubois** [comment]
> However, we currently lack detailed error information on the frontend at this point.

I know; I was talking about a general statement. Right now the dialog says:

```
Rancher Desktop has already performed a Factory Reset and will now exit.
Please restart Rancher Desktop to try restoring the snapshot again.
```

I wanted to change it to something like:

```
Rancher Desktop has already performed a Factory Reset and will now exit.
Please try to address the problem that caused the failure.
Then restart Rancher Desktop and try to restore the snapshot again.
```

Without the step in between, we are just telling the user to retry the failed operation, which will likely fail the same way again.

Or maybe I'm overthinking this, but in general it helps to be as explicit as possible. Remember that the user is already stressed because they are being denied access to their saved data and may be following the instructions quite literally.

**Comment by rak-phillip** [comment]
> I wanted to change it to something like:
> 
> ```
> Rancher Desktop has already performed a Factory Reset and will now exit.
> Please try to address the problem that caused the failure.
> Then restart Rancher Desktop and try to restore the snapshot again.
> ```

Thanks for the example, I originally understood the ask as this message being catered to the actual error message itself and adding a generic error message like you suggest makes more sense 🙂

**Review by ericpromislow — APPROVED** [review]
I found the combination of the specific error message in the failure (I did a `chmod 000 lima.yml` in the snapshot subdir) and the generic message clear as to what's going on.

**Review by adamkpickering — APPROVED** [review]
LGTM :rocket: :rocket:

**Pull request merged**
