### PR TITLE
flatpak: Use id instead of app-id

### PR DESCRIPTION
**Pull request by shubhisroking**
`app-id` is deprecated

### CODE REVIEW

**Comment by adamkpickering** [comment]
Hello @shubhisroking and thank you for your contribution!

I am having trouble finding documentation that says that `app-id` is deprecated. The [documentation I did find](https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html) seems to say that either `id` or `app-id` is acceptable. I may be missing something though - can you direct me to the place you got this information?

A side note: you are probably already aware, but in case you aren't: we don't build a flatpak version of Rancher Desktop at the moment. We'd like to investigate this further, but it hasn't been the highest priority.

**Review by ericpromislow — COMMENTED** [review]
I would like to see documentation of the deprecation before making this change. 

OTOH the linux and macos e2e tests pass locally for me.

**Comment by jandubois** [comment]
> I would like to see documentation of the deprecation before making this change.

https://github.com/flatpak/flatpak-builder/pull/482, in particular https://github.com/flatpak/flatpak-builder/pull/482/commits/9b1736f5b1926dd180322eaefb57930837d29153

**Review by ericpromislow — APPROVED** [review]
ok

**Review by adamkpickering — APPROVED** [review]

**Pull request merged**
