### PR TITLE
Add docker-compose integration.

### PR DESCRIPTION
**Pull request by ericpromislow**
- Download the docker-compose plugin
- Implement a silent integration for the plugin

Signed-off-by: Eric Promislow <epromislow@suse.com>

### CODE REVIEW

**Review by rak-phillip — APPROVED** [review]
LGTM - Used a simple example to test on linux, and windows. We discussed the discrepancy between `docker-compose` and `docker compose`; `docker compose` is the way forward.

**Comment by rak-phillip** [comment]
After working out some issues with my environment, I was able to test on macOS. 

I initially encountered this error when running `docker compose up`:

```
$ docker compose up
[+] Running 0/0
 ⠋ redis Pulling                                                                           0.0s
error getting credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
```

Confirmed that I was running docker compose v2.2.3 before deleting `~/.docker` and restarting Rancher Desktop to resolve the issue, but failed to take a backup beforehand..

**Comment by nathanweeks** [comment]
> After working out some issues with my environment, I was able to test on macOS.
> 
> I initially encountered this error when running `docker compose up`:
> 
> ```
> $ docker compose up
> [+] Running 0/0
>  ⠋ redis Pulling                                                                           0.0s
> error getting credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
> ```

This is related to: https://github.com/rancher-sandbox/rancher-desktop/issues/1124#issuecomment-1021486098

Following the above comment, I worked around this by:
1. Cownloading the most recent `docker-credential-osxkeychain` (though instead of using brew, downloading from https://github.com/docker/docker-credential-helpers/releases/tag/v0.6.4 , and moving the untarred executable to to `/usr/local/bin`), and
2. Updating `~/.docker/config.json`, changing the value of `credsStore` from `desktop` to `osxkeychain`

**Comment by blueboxes** [comment]
I have found that visual studio 2022 when you debug launch via a compose it calls `docker-compose` (rather than `docker compose`) so when manually installing I had to add the plugins folder to the windows path env var. Has this been concidered?

**Pull request merged**
