### PR TITLE
Moproxy support for noproxy policies modification from graphical interface

### LINKED ISSUE #5100: Support for managing hosts in the noproxy list from preferences
We want to be able to manage the noproxy list from the preferences dialog, so that hosts that should not be proxied can be specified easily from the UI.

## Proposal

- Display the noproxy list in the WSL Proxy tab alongside other controls
- Manage hosts in the noproxy list via a `textarea`

## Acceptance Criteria

- [ ] Existing hosts in the noproxy list are displayed in a scrollable and easily viewable format
- [ ] Users can add new hosts to the noproxy list
- [ ] Users can delete hosts from the noproxy list
- [ ] Users can edit existing hosts in the noproxy list
- [ ] Users can bulk-add multiple hosts to the noproxy list by providing a comma-delimited string

## Mockup

Drawing 2023-07-05 06 41 30 excalidraw

### PR DESCRIPTION
**Pull request by tperale**
Add support for noproxy policies from the rancher-desktop settings window.

Screenshot_win10_2023-06-07_14:59:47

The input box is already full with the default addresses. I'm open to any proposition to make this more clear.

Next step of the PR https://github.com/rancher-sandbox/rancher-desktop/pull/4697 

https://github.com/rancher-sandbox/rancher-desktop/issues/4603

Fixes #5100

### CODE REVIEW

**Comment by Nino-K** [comment]
@rak-phillip can you please provide your feedback from our last week meeting so @tperale is aware of the changes that need to be made? Thanks

**Comment by rak-phillip** [comment]
@Nino-K @tperale of course, I've created issue #5100 and added it to Epic #4603 so that we can track this work in a more structured way outside of this PR.

**Comment by tperale** [comment]
@Nino-K @rak-phillip Updated this branch to fit the noproxy box on the right of the proxy preference. It doesn't really match the mockup provided but kept it simple with a `textarea`. The way I understood the mockup it would requires to use a selector with editable options on click but I won't have much time to work on rancher-desktop in the coming month.

2023-07-31-131245_625x279_scrot

**Comment by jandubois** [comment]
> I won't have much time to work on rancher-desktop in the coming month.

Thank you for all your work!

I've re-triggered the CI tests, as they have been failing; not sure if there is an issue with the PR, or if this is just flakiness.

Assuming the tests are going to pass, @rak-phillip will review this PR, and merge if it seems fine.

We'll then create a separate issue to transform the textbox into the requested listbox form, and schedule this for other team members, at a later time.

**Comment by rak-phillip** [comment]
I am noting some unit test errors and merge conflicts, otherwise I think the proposed change with the `textarea` will work fine for the time being. 

@tperale Are you available to make the remaining changes to this PR so that it passes CI? If you're not, I'd like to make sure that you are comfortable with the Rancher Desktop team picking up the remaining work. I think you've made great contributions here and I'd like to see this merged.

**Comment by gaktive** [comment]
Handing over to @s0nea to push over the finish line. @rak-phillip will clean up the associated parent ticket #5100 to reflect the current state and then create a new one to revise the work.

**Review by rak-phillip — APPROVED** [review]
LGTM - I would like to see some extra documentation, otherwise I think this is good to merge.

**Review by rak-phillip — APPROVED** [review]

**Pull request merged**
